# -*- coding: utf-8 -*-
"""English strings for document operations (pdflx.features / pdflx.dialogs).

Other languages fall back to English for these keys until translated; the
main menu group labels are translated below.
"""

STRINGS_EN = {
    # Generic
    'btn_add': 'Add', 'btn_choose': 'Choose…', 'btn_collate': 'Collate', 'btn_create': 'Create',
    'btn_dismiss': 'Dismiss', 'btn_export': 'Export…', 'btn_extract': 'Extract', 'btn_find_remove': 'Find and Remove',
    'btn_flatten': 'Flatten', 'btn_insert': 'Insert', 'btn_scan': 'Scan', 'btn_split': 'Split…',
    'yes': 'Yes', 'no': 'No', 'dpi': 'Resolution (DPI)', 'margin_pt': 'Margin (pt)',
    'keep_proportions': 'Keep proportions', 'paper_size': 'Paper size', 'paper_landscape': 'Landscape',
    'untitled_document': 'Untitled Document', 'output': 'Output', 'output_destination': 'Destination',
    'output_new_tab': 'Open in a new tab', 'output_file': 'Save as a file', 'output_zip': 'ZIP archive',
    'output_folder': 'Folder', 'saved_to': 'Saved to {}', 'file_none_selected': 'No file selected',
    'preview_refresh': 'Refresh preview', 'progress_working': 'Working…', 'progress_count': '{} of {}',
    'progress_cancelling': 'Cancelling…', 'progress_cancelled': 'The operation was cancelled.',
    'range_pages': 'Pages', 'range_all': 'All', 'range_current': 'Current', 'range_selected': '{} page(s) selected',
    'filter_documents': 'Documents and images', 'filter_convertible': 'XPS, EPUB, MOBI, FB2, CBZ, SVG, text, images',
    'filter_supported': 'All supported files',
    'pos_after_current': 'After the current page', 'pos_before_current': 'Before the current page',
    'pos_start': 'At the beginning', 'pos_end': 'At the end',
    'colorspace_gray': 'Grayscale', 'colorspace_rgb': 'RGB', 'colorspace_cmyk': 'CMYK',

    # Errors
    'err_no_doc_to_save': 'There is no document to save.',
    'err_incremental_unavailable': 'Changes can only be appended to the unencrypted, unrepaired PDF file this '
                                   'document was opened from.',
    'err_cannot_delete_all_pages': 'A document must keep at least one page.',
    'err_choose_file': 'Choose a file first.', 'err_edit_not_allowed': 'Switch to Edit mode to change this document.',
    'err_form_values': 'Some form values are invalid. Correct them first.',
    'err_insert_encrypted': 'Password-protected files cannot be used here. Remove the password first.',
    'err_need_two_pages': 'This needs a document with at least two pages.',
    'err_no_annotations': 'This document has no annotations.', 'err_open_file': 'Could not open {}: {}',
    'err_overlay_same_file': 'Choose a different PDF for the overlay.',
    'err_overwrite_open_file': 'Choose a different file name; the open document cannot be overwritten here.',
    'err_owner_required': 'Open the document with its owner password to change security.',
    'err_pages_have_editor_objects': 'Pages {} contain editable objects added in pdfLX. Flatten or remove them '
                                     'before changing page geometry so they are not misplaced.',
    'err_pyhanko_missing': 'Signature verification requires pyHanko. Install the application dependencies.',

    # Menus
    'menu_main_tip': 'Main menu', 'menu_group_document': 'Document', 'menu_group_pages': 'Pages',
    'menu_group_annotate': 'Annotate', 'menu_group_insert': 'Insert and Forms', 'menu_group_protect': 'Protect',
    'menu_group_tools': 'Tools', 'menu_view': 'View', 'menu_reader_mode': 'Reading colors',
    'reader_mode_normal': 'Original colors', 'reader_mode_night': 'Night', 'reader_mode_sepia': 'Sepia',
    'reader_mode_contrast': 'High contrast',
    'menu_open_other_format': 'Open Other Format…', 'menu_images_to_pdf': 'Create PDF from Images…',
    'menu_save_incremental': 'Save Incrementally', 'menu_document_info': 'Document Information…',
    'menu_viewer_settings': 'Viewer Settings…', 'menu_generate_bookmarks': 'Generate Bookmarks from Headings…',
    'menu_links': 'Links…', 'menu_attachments': 'Attachments…', 'menu_layers': 'Layers…',
    'menu_insert_pages': 'Insert Pages from File…', 'menu_extract_pages': 'Extract Pages…',
    'menu_split_document': 'Split Document…', 'menu_reverse_pages': 'Reverse Page Order',
    'menu_collate_pages': 'Collate Scanned Pages…', 'menu_remove_blank_pages': 'Remove Blank Pages…',
    'menu_remove_rotation': 'Make Rotation Permanent…', 'menu_resize_pages': 'Resize Pages…',
    'menu_page_boxes': 'Page Boxes…', 'menu_nup_pages': 'N-Up and Booklet…',
    'menu_headers_footers': 'Headers, Footers and Bates…', 'menu_overlay_pages': 'Background and Overlay…',
    'menu_page_labels': 'Page Labels…', 'menu_add_markup': 'Shapes, Text Boxes and Attachments…',
    'menu_export_annotations': 'Export Annotations…', 'menu_import_annotations': 'Import Annotations…',
    'menu_comment_summary': 'Comment Summary…', 'menu_flatten_annotations': 'Flatten Annotations…',
    'menu_security': 'Password and Permissions…', 'menu_verify_signatures': 'Verify Signatures…',
    'menu_sanitize': 'Sanitize Document…', 'menu_hidden_text': 'Find Hidden Text…',
    'menu_rasterize': 'Flatten Pages to Images…', 'menu_advanced_search': 'Advanced Search…',
    'menu_compare': 'Compare Documents…', 'menu_text_style': 'Text Properties…',
    'menu_snapshot': 'Copy Selection as Image', 'menu_ocr': 'Recognize Text (OCR)…',
    'menu_optimize': 'Reduce File Size…', 'menu_recolor': 'Convert Colors…',
    'menu_export_structured': 'Structured Text…', 'menu_export_images': 'Pages as Images…',
    'menu_export_tables': 'Tables as Markdown or JSON…',

    # Signed documents
    'signed_save_title': 'This PDF is digitally signed',
    'signed_save_body': 'Signed fields: {}. Rewriting the file invalidates these signatures.',
    'signed_save_append_hint': 'Append Changes adds your edits as a new revision and keeps the signed revision '
                               'intact. Verifiers will still report that the document changed after signing.',
    'signed_save_copy': 'Save as Copy…', 'signed_save_append': 'Append Changes',
    'signed_save_rewrite': 'Rewrite File',

    # Insert / extract / split
    'insert_source': 'Source', 'insert_source_hint': 'PDF, XPS, EPUB, images, and other supported files.',
    'insert_file': 'File', 'insert_source_pages': 'Pages to insert (empty = all)', 'insert_position': 'Position',
    'extract_delete_after': 'Delete extracted pages from this document',
    'extract_delete_hint': 'Available in Edit mode. Undo restores them.',
    'split_method': 'Split method', 'split_every': 'Every N pages', 'split_ranges': 'Custom ranges',
    'split_bookmarks': 'At top-level bookmarks', 'split_single': 'One file per page',
    'split_pages_per_file': 'Pages per file', 'split_range_groups': 'Ranges, separated by ; (e.g. 1-3; 4-10)',
    'split_result': 'Result', 'split_preview': '{} file(s)', 'split_choose_folder': 'Choose a folder for the parts',

    # Order / blanks / geometry
    'collate_title': 'Interleave front and back scans',
    'collate_hint': 'For a stack scanned as all fronts followed by all backs.',
    'collate_fronts': 'Number of front pages', 'collate_backs_reversed': 'Backs were scanned in reverse order',
    'collate_result': 'New order',
    'blank_title': 'Detect blank pages', 'blank_hint': 'Pages with annotations or form fields are never removed.',
    'blank_threshold': 'Blank when this share is background (%)',
    'blank_threshold_hint': 'Lower values also remove pages with specks or scan noise.',
    'blank_none_found': 'No blank pages were found.',
    'rotation_title': 'Make page rotation permanent',
    'rotation_hint': 'Rewrites rotated pages so they read upright with a rotation of 0°. Useful for tools that '
                     'ignore the rotation setting.',
    'rotation_none': 'None of the selected pages is rotated.',
    'resize_title': 'Place pages on a uniform paper size',
    'resize_hint': 'Creates a new document. Links and annotations on resized pages are not carried over.',
    'nup_layout': 'Layout', 'nup_hint': 'Creates a new document for printing.', 'nup_sheet': 'Sheet',
    'nup_2': '2 pages per sheet', 'nup_4': '4 pages per sheet', 'nup_6': '6 pages per sheet',
    'nup_9': '9 pages per sheet', 'nup_16': '16 pages per sheet',
    'nup_booklet': 'Booklet (saddle stitch, print double-sided on the short edge)',
    'nup_borders': 'Draw page borders', 'nup_columns_first': 'Fill columns first',
    'overlay_source': 'Overlay document', 'overlay_hint': 'Use letterhead or stationery behind pages, or a '
                                                           'form or mark in front of them.',
    'overlay_file': 'PDF file', 'overlay_source_page': 'Page of the overlay document', 'overlay_placement': 'Placement',
    'overlay_behind': 'Behind the content (background)', 'overlay_front': 'In front of the content (overlay)',

    # Headers and footers
    'hf_text': 'Text', 'hf_placeholders': 'Placeholders: {page}, {total}, {bates}, {file}, {date}',
    'hf_top_left': 'Top left', 'hf_top_center': 'Top center', 'hf_top_right': 'Top right',
    'hf_bottom_left': 'Bottom left', 'hf_bottom_center': 'Bottom center', 'hf_bottom_right': 'Bottom right',
    'hf_style': 'Style', 'hf_bates': 'Bates numbering', 'hf_bates_hint': 'Insert the number with {bates}.',
    'hf_bates_enable': 'Enable Bates numbering', 'hf_bates_prefix': 'Prefix', 'hf_bates_start': 'Start number',
    'hf_bates_digits': 'Digits', 'hf_bates_suffix': 'Suffix',

    # Labels and boxes
    'labels_rules': 'Numbering rules',
    'labels_hint': 'Logical page numbers shown by PDF readers, e.g. i–iv for front matter, then 1, 2, 3.',
    'labels_add_rule': 'Add rule', 'labels_remove_rule': 'Remove rule', 'labels_preview': 'Preview',
    'labels_start_page': 'First physical page of this rule', 'labels_prefix': 'Prefix',
    'labels_first_number': 'Number of the first page', 'labels_from_page': 'From page',
    'labels_from_number': 'start at',
    'label_style_D': '1, 2, 3', 'label_style_r': 'i, ii, iii', 'label_style_R': 'I, II, III',
    'label_style_a': 'a, b, c', 'label_style_A': 'A, B, C', 'label_style_none': 'Prefix only',
    'boxes_current': 'Current boxes (page {})', 'boxes_hint': 'Values in points. Bleed, trim, and art boxes are '
                                                               'used by print production workflows.',
    'boxes_set_inset': 'Inset from the crop box',
    'box_mediabox': 'Media box', 'box_cropbox': 'Crop box', 'box_bleedbox': 'Bleed box', 'box_trimbox': 'Trim box',
    'box_artbox': 'Art box',
    'box_trimbox_hint': 'The finished page size after trimming.',
    'box_bleedbox_hint': 'The area to which content may extend for trimming tolerance.',
    'box_artbox_hint': 'The meaningful content area.',

    # Annotations
    'markup_type': 'Annotation', 'markup_text': 'Text', 'markup_area': 'Position on the page',
    'markup_hint_selection': 'The annotation uses the area selected on the page.',
    'markup_hint_no_selection': 'Tip: select an area on the page first, or enter its position below.',
    'markup_rectangle': 'Rectangle', 'markup_ellipse': 'Ellipse', 'markup_line': 'Line', 'markup_arrow': 'Arrow',
    'markup_double_arrow': 'Double arrow', 'markup_textbox': 'Text box (typewriter)', 'markup_callout': 'Callout',
    'markup_caret': 'Insertion mark', 'markup_attachment': 'File attachment',
    'markup_attachment_file': 'File to attach', 'markup_style': 'Style', 'markup_stroke': 'Line and text color',
    'markup_fill_enable': 'Fill', 'markup_fill': 'Fill color', 'markup_line_width': 'Line width',
    'markup_dashed': 'Dashed line',
    'flatten_annotations_body': 'Burn {} annotation(s) into the page content? They will no longer be editable '
                                'as comments. Form fields are kept. You can undo this until you close the document.',
    'summary_preview': 'Preview',

    # Security
    'security_current': 'Current protection', 'security_encryption': 'Encryption', 'security_none': 'None',
    'security_allowed': 'Allowed', 'security_passwords': 'Passwords',
    'security_passwords_hint': 'The open password is optional. The owner password is required to enforce '
                               'permissions.',
    'security_open_password': 'Password to open', 'security_owner_password': 'Owner password',
    'security_method': 'Encryption', 'security_permissions': 'Permissions',
    'security_permissions_hint': 'Reader software decides how strictly permissions are enforced.',
    'security_remove': 'Remove protection',
    'security_remove_hint': 'Saves an unencrypted copy. Requires the owner password.',
    'security_remove_button': 'Save Unprotected Copy…', 'security_save_protected': 'Save Protected Copy…',
    'perm_print': 'Print', 'perm_print_hq': 'Print in high quality', 'perm_modify': 'Change content',
    'perm_copy': 'Copy text and images', 'perm_accessibility': 'Extract text for accessibility',
    'perm_annotate': 'Add and change comments', 'perm_form': 'Fill in form fields',
    'perm_assemble': 'Insert, delete, and rotate pages',
    'sanitize_remove': 'Remove', 'sanitize_hint': 'Creates a cleaned copy; the open document is not changed.',
    'sanitize_note': 'Images partly covered by redactions are blanked pixel by pixel. Sanitization does not '
                     'remove information that is visible on the page; use Redact for that.',
    'sanitize_save': 'Save Sanitized Copy…',
    'scrub_metadata': 'Document information (title, author, …)', 'scrub_xml_metadata': 'XMP metadata',
    'scrub_javascript': 'JavaScript', 'scrub_embedded_files': 'Embedded files',
    'scrub_attached_files': 'File-attachment annotations', 'scrub_remove_links': 'Links',
    'scrub_thumbnails': 'Embedded page thumbnails', 'scrub_reset_fields': 'Reset form fields to their defaults',
    'scrub_reset_responses': 'Annotation replies', 'scrub_hidden_text': 'Hidden (invisible) text',
    'scrub_redactions': 'Apply pending redactions', 'scrub_clean_pages': 'Clean and compact page content',
    'hidden_title': 'Text a reader would not see',
    'hidden_hint': 'Invisible, white, transparent, tiny, or off-page text. White text may be legitimate on dark '
                   'backgrounds; review each result.',
    'hidden_summary': 'Result', 'hidden_not_scanned': 'Not scanned yet.', 'hidden_found': '{} item(s) found.',
    'hidden_none': 'No hidden text was found.',
    'hidden_reason_invisible': 'Invisible', 'hidden_reason_white': 'White', 'hidden_reason_transparent': 'Transparent',
    'hidden_reason_tiny': 'Tiny', 'hidden_reason_off-page': 'Off the page',
    'rasterize_title': 'Replace pages with images',
    'rasterize_hint': 'Creates a new document. Text, links, comments, and form fields on these pages become part '
                      'of a picture and can no longer be selected or searched.',
    'rasterize_gray': 'Grayscale',

    # Signature verification
    'verify_hint': 'Checks the file on disk: integrity, signer certificate, trust, and changes after signing.',
    'verify_hint_modified': 'The document has unsaved changes; the saved file on disk is verified.',
    'verify_trust': 'Trust', 'verify_system_roots': 'Trust system certificate authorities',
    'verify_extra_roots': 'Additional trusted certificates',
    'verify_extra_roots_hint': 'PEM or DER files, for example your organization\'s root certificate.',
    'verify_results': 'Signatures', 'verify_run': 'Verify Again', 'verify_running': 'Verifying…',
    'verify_none': 'This document has no digital signatures.', 'verify_unnamed': 'Unnamed signature',
    'verify_status_valid': 'Valid: unchanged since signing, signer trusted.',
    'verify_status_untrusted': 'Intact, but the signer is not trusted.',
    'verify_status_modified': 'Intact, but the document changed after signing.',
    'verify_status_invalid': 'Invalid: the signed content was altered or cannot be verified.',
    'verify_signer': 'Signer', 'verify_issuer': 'Issuer', 'verify_time': 'Signing time (claimed by signer)',
    'verify_intact': 'Signed data intact', 'verify_valid': 'Cryptographically valid', 'verify_trusted': 'Trusted',
    'verify_coverage': 'Coverage', 'verify_modifications': 'Changes after signing',

    # Conversion and optimization
    'images_source': 'Images', 'images_hint': 'One page per image; multi-page TIFFs add one page per frame.',
    'images_choose': 'Image files', 'images_layout': 'Page layout', 'images_native_size': 'Same as each image',
    'images_fit': 'Fit', 'images_fit_keep': 'Fit and keep proportions', 'images_fit_stretch': 'Stretch to fill',
    'optimize_images': 'Images', 'optimize_images_hint': 'Downsampling reduces the size of photos and scans.',
    'optimize_downsample': 'Downsample and recompress images', 'optimize_target_dpi': 'Target resolution (DPI)',
    'optimize_jpeg_quality': 'JPEG quality', 'optimize_gray_images': 'Convert images to grayscale',
    'optimize_other': 'Other', 'optimize_subset_fonts': 'Subset embedded fonts',
    'optimize_subset_hint': 'Keeps only the characters used. Text added later may need a different font.',
    'optimize_object_streams': 'Compress document structure',
    'optimize_remove_metadata': 'Remove metadata and thumbnails', 'optimize_result': 'Result',
    'optimize_size': 'Size', 'optimize_not_run': 'Press Analyze to estimate the result.',
    'optimize_size_result': '{} → {} ({:.0f}% smaller)', 'optimize_analyze': 'Analyze',
    'optimize_save': 'Save Optimized Copy…', 'optimize_save_now': 'Save Optimized Copy…',
    'optimize_running': 'Optimizing…',
    'recolor_title': 'Convert all colors', 'recolor_hint': 'Creates a new document with text, graphics, and images '
                                                           'converted to the chosen color space.',
    'recolor_target': 'Color space',
    'ocr_title': 'Make scanned pages searchable',
    'ocr_hint': 'Adds an invisible text layer and keeps the page appearance. Creates a new document.',
    'ocr_language': 'Language', 'ocr_extra_languages': 'Additional languages (e.g. deu+fra)',
    'ocr_skip_text_pages': 'Skip pages that already contain text', 'ocr_run': 'Recognize',
    'ocr_running': 'Recognizing text…', 'ocr_unavailable': 'OCR is not available',
    'ocr_nothing_done': 'All selected pages already contain text; nothing was recognized.',
    'export_image_format': 'Format', 'export_colorspace': 'Color space',
    'export_transparent': 'Transparent background', 'export_transparent_hint': 'PNG and PAM only.',
    'structured_title': 'Export text with structure',
    'structured_hint': 'Markdown recognizes headings by font size and includes detected tables.',
    'structured_format': 'Format', 'structured_reading_order': 'Sort into reading order',
    'structured_reading_order_hint': 'Orders text top-to-bottom, left-to-right. Turn off to keep the content '
                                     'stream order.',
    'tables_title': 'Detected tables', 'tables_hint': 'Tables are detected from ruling lines or text alignment.',
    'tables_csv_zip': 'CSV files (ZIP)', 'tables_strategy': 'Detection',
    'tables_strategy_lines': 'Ruling lines', 'tables_strategy_text': 'Text alignment',

    # Information and settings
    'info_overview': 'Overview', 'info_general': 'General', 'info_features': 'Contents and security',
    'info_file': 'File', 'info_file_size': 'File size', 'info_pages': 'Pages', 'info_page_sizes': 'Page sizes',
    'info_pdf_version': 'PDF version', 'info_producer': 'Producer', 'info_created': 'Created',
    'info_modified': 'Modified', 'info_encryption': 'Encryption', 'info_signed_fields': 'Signed fields',
    'info_form': 'Form fields', 'info_tagged': 'Tagged PDF', 'info_attachments': 'Attachments',
    'info_layers': 'Layers', 'info_javascript': 'JavaScript', 'info_xmp': 'XMP metadata',
    'info_fast_web': 'Fast web view', 'info_repaired': 'Repaired on opening', 'info_fonts': 'Fonts',
    'info_fonts_hint': 'Fonts that are not embedded are substituted by the reader.',
    'info_embedded': 'embedded', 'info_not_embedded': 'not embedded', 'info_subset': 'subset',
    'info_extract_font': 'Save font file…', 'info_statistics': 'Statistics',
    'info_compute_statistics': 'Count words, images, and links',
    'stat_pages': 'Pages', 'stat_words': 'Words', 'stat_characters': 'Characters (without spaces)',
    'stat_images': 'Image placements', 'stat_links': 'Links', 'stat_annotations': 'Annotations',
    'stat_form_fields': 'Form fields',
    'viewer_opening': 'When the document opens', 'viewer_hint': 'Stored in the PDF and honoured by most readers.',
    'viewer_page_mode': 'Show', 'viewer_page_layout': 'Page layout', 'viewer_window': 'Window',
    'viewer_document': 'Document', 'viewer_language': 'Language (e.g. en-US)',
    'viewer_need_appearances': 'Ask readers to regenerate form field appearances',
    'viewer_need_appearances_hint': 'Helps when field values look different in other readers.',
    'pagemode_UseNone': 'Page only', 'pagemode_UseOutlines': 'Bookmarks panel',
    'pagemode_UseThumbs': 'Thumbnails panel', 'pagemode_FullScreen': 'Full screen',
    'pagemode_UseOC': 'Layers panel', 'pagemode_UseAttachments': 'Attachments panel',
    'pagelayout_SinglePage': 'Single page', 'pagelayout_OneColumn': 'Continuous',
    'pagelayout_TwoColumnLeft': 'Two pages, continuous', 'pagelayout_TwoColumnRight': 'Two pages, continuous, with cover',
    'pagelayout_TwoPageLeft': 'Two pages', 'pagelayout_TwoPageRight': 'Two pages, with cover',
    'viewerpref_DisplayDocTitle': 'Show the document title instead of the file name',
    'viewerpref_FitWindow': 'Fit the window to the first page', 'viewerpref_CenterWindow': 'Center the window',
    'viewerpref_HideToolbar': 'Hide the reader toolbar', 'viewerpref_HideMenubar': 'Hide the reader menu bar',

    # Bookmarks
    'bookmark_indent': 'Make child of the previous bookmark', 'bookmark_outdent': 'Move one level up',
    'bookmark_move_up': 'Move up', 'bookmark_move_down': 'Move down',
    'bookmarks_replace': 'Apply', 'autotoc_settings': 'Detection',
    'autotoc_hint': 'Headings are recognized as text larger than the body text.',
    'autotoc_levels': 'Heading levels', 'autotoc_ratio': 'Minimum size relative to body text',
    'autotoc_mode': 'Existing bookmarks', 'autotoc_replace': 'Replace', 'autotoc_append': 'Keep and append',
    'autotoc_preview': 'Proposed bookmarks', 'autotoc_none': 'No headings were detected.',

    # Links, attachments, layers
    'links_add': 'Add link', 'links_add_hint': 'Select the clickable area on the page, then add the link.',
    'links_view_only': 'Switch to Edit mode to add or remove links.',
    'links_type': 'Link type', 'links_target': 'Web address', 'links_target_page': 'Target page',
    'links_named_action': 'Action', 'links_target_file': 'Target file', 'links_add_button': 'Add Link',
    'links_detect_urls': 'Link Web Addresses in Text', 'links_existing': 'Links', 'links_scope': 'Show',
    'links_scope_page': 'Current page', 'links_scope_all': 'All pages', 'links_none': 'No links.',
    'links_go': 'Go to page', 'links_delete': 'Delete link',
    'links_need_selection': 'Select the clickable area on the page first.',
    'link_uri': 'Web address', 'link_goto': 'Page in this document', 'link_gotor': 'Page in another PDF',
    'link_launch': 'Open file', 'link_named': 'Named action',
    'named_FirstPage': 'First page', 'named_LastPage': 'Last page', 'named_NextPage': 'Next page',
    'named_PrevPage': 'Previous page',
    'attachments_title': 'Embedded files', 'attachments_hint': 'Files carried inside the PDF.',
    'attachments_add': 'Add Files…', 'attachments_save': 'Save…', 'attachments_remove': 'Remove',
    'attachments_none': 'No embedded files.',
    'layers_title': 'Layers (optional content)', 'layers_hint': 'Turn layers on or off.',
    'layers_none': 'This document has no layers.', 'layers_new': 'New layer', 'layers_new_name': 'Name',
    'layers_apply_view': 'Apply to View',

    # Compare, search, style, snapshot
    'compare_with': 'Compare with', 'compare_hint': 'Compares the open document with another PDF.',
    'compare_file': 'Other PDF', 'compare_method': 'Method', 'compare_text': 'Text (word by word)',
    'compare_visual': 'Appearance (pixel by pixel)', 'compare_mark': 'Open the other PDF with changes highlighted',
    'compare_mark_hint': 'Text comparison only.', 'compare_results': 'Differences', 'compare_summary': 'Summary',
    'compare_not_run': 'Not compared yet.', 'compare_run': 'Compare', 'compare_running': 'Comparing…',
    'compare_identical': 'No differences were found.',
    'compare_text_summary': '{} change(s); {:.1f}% similar.', 'compare_visual_summary': '{} page(s) differ.',
    'compare_insert': 'Added', 'compare_delete': 'Removed', 'compare_replace': 'Changed',
    'compare_marked_opened': 'Opened the other document with changes highlighted.',
    'search_query': 'Search', 'search_regex': 'Regular expression', 'search_regex_hint': 'Python syntax, e.g. '
                                                                                         r'\d{4}-\d{2}',
    'search_case': 'Match case', 'search_whole_word': 'Whole words only', 'search_results': 'Results',
    'search_find_all': 'Find All', 'search_found': '{} match(es).', 'search_enter_query': 'Enter text to find.',
    'search_option_case': 'Match case', 'search_option_word': 'Whole words only',
    'search_option_regex': 'Regular expression',
    'text_style_details': 'Text under the selection', 'text_style_text': 'Text', 'text_style_font': 'Font',
    'text_style_size': 'Size', 'text_style_color': 'Color', 'text_style_bold': 'Bold',
    'text_style_italic': 'Italic', 'text_style_opacity': 'Opacity', 'text_style_render': 'Rendering',
    'text_style_same': 'Same font and size ({})',
    'text_style_need_selection': 'Select some text on the page first.',
    'render_mode_0': 'Fill', 'render_mode_1': 'Outline', 'render_mode_2': 'Fill and outline',
    'render_mode_3': 'Invisible',
    'snapshot_need_selection': 'Select an area on the page first.',

    # Status messages
    'status_new_tab_created': 'Created in a new tab. Save it to keep it.',
    'status_pages_inserted': 'Inserted {} page(s).', 'status_pages_extracted': 'Extracted {} page(s).',
    'status_pages_deleted': 'Deleted {} page(s).', 'status_split_done': 'Saved {} file(s) to {}.',
    'status_pages_reversed': 'Page order reversed.', 'status_pages_collated': 'Pages collated.',
    'status_blank_removed': 'Removed {} blank page(s): {}.', 'status_rotation_removed': 'Updated {} page(s).',
    'status_overlay_applied': 'Applied to {} page(s).', 'status_headers_applied': 'Added to {} page(s).',
    'status_labels_saved': 'Page labels updated.', 'status_boxes_saved': 'Page boxes updated on {} page(s).',
    'status_markup_added': 'Annotation added.', 'status_annotations_exported': 'Annotations exported.',
    'status_annotations_imported': 'Imported {} annotation(s); {} skipped.',
    'status_annotations_flattened': 'Flattened {} annotation(s).',
    'status_security_saved': 'Protected copy saved.', 'status_security_removed': 'Unprotected copy saved.',
    'status_sanitized': 'Sanitized copy saved.', 'status_converted': 'Converted {}.',
    'status_images_combined': 'Combined {} image(s).', 'status_optimized': 'Optimized copy saved.',
    'status_ocr_done': 'Recognized text on {} page(s).', 'status_images_exported': 'Exported {} page(s).',
    'status_viewer_settings_saved': 'Viewer settings updated.',
    'status_bookmarks_generated': 'Created {} bookmark(s).', 'status_link_added': 'Link added.',
    'status_links_detected': 'Linked {} web address(es).', 'status_layers_saved': 'Layers updated.',
    'status_snapshot_copied': 'Copied a {}×{} image to the clipboard.',

    # Forms structure and scripts
    'menu_form_structure': 'Form Structure and Scripts…',
    'forms_js_notice': 'pdfLX does not run JavaScript. Scripts listed here run in other PDF readers.',
    'forms_hierarchy': 'Field hierarchy',
    'forms_hierarchy_hint': 'Group top-level fields under a parent so they share a name prefix (parent.child).',
    'forms_parent_name': 'New parent name', 'forms_group_selected': 'Group Selected Fields',
    'forms_ungroup': 'Ungroup', 'forms_group': 'group', 'forms_none': 'This document has no form fields.',
    'forms_scripts': 'JavaScript', 'forms_no_scripts': 'No JavaScript was found.',
    'forms_remove_script': 'Remove', 'forms_add_script': 'Add or replace a field script',
    'forms_add_script_hint': 'An empty script removes the event handler.', 'forms_field': 'Field',
    'forms_event': 'Event', 'forms_save_script': 'Save Script', 'forms_choose_field': 'Choose a field.',
    'status_forms_updated': 'Form updated.',
    'form_multi_select_hint': 'Select every value that applies.',
    # Comments sidebar
    'comments_filter_placeholder': 'Filter by text or author', 'comments_filter_all_types': 'All types',
    'comments_filter_all_states': 'Any status', 'comments_filter_current_page': 'Current page only',
    'comments_no_match': 'No comments match the filters.', 'comments_reply': 'Reply',
    'comments_reply_placeholder': 'Write a reply', 'comments_set_state': 'Set review status',
    'comments_properties': 'Annotation Properties',
    'comments_state_none': 'No status', 'comments_state_None': 'Clear status',
    'comments_state_Accepted': 'Accepted', 'comments_state_Rejected': 'Rejected',
    'comments_state_Cancelled': 'Cancelled', 'comments_state_Completed': 'Completed',
    'annot_subject': 'Subject', 'annot_flags': 'Behaviour',
    'annot_flags_hint': 'Readers interpret these flags; some ignore a few of them.',
    'annot_flag_hidden': 'Hidden', 'annot_flag_print': 'Print with the page',
    'annot_flag_no_zoom': 'Keep size when zooming', 'annot_flag_no_rotate': 'Keep upright when rotating',
    'annot_flag_no_view': 'Do not show on screen', 'annot_flag_read_only': 'Read-only',
    'annot_flag_locked': 'Locked (cannot be moved or deleted)', 'annot_flag_locked_contents': 'Contents locked',
    # Redaction options
    'redact_replacement': 'Replacement text', 'redact_fill': 'Fill color', 'redact_no_fill': 'No fill (transparent)',
    'redact_images': 'Images under the area',
    'redact_images_pixels': 'Blank only the covered pixels',
    'redact_images_remove': 'Remove each overlapping image entirely',
    'redact_images_keep': 'Keep images (not secure)',

    # Graphics
    'menu_export_diagram': 'Diagram or Selection…', 'menu_export_vector_svg': 'Vector Drawings as SVG',
    'menu_images_manager': 'Images…',
    'diagram_none': 'This page has no vector diagrams. Select an area to export it.',
    'diagram_area': 'Area', 'diagram_hint': 'Vector drawings are grouped into diagrams automatically.',
    'diagram_selection': 'Selected area', 'diagram_cluster': 'Diagram {} ({}×{} pt)',
    'diagram_snap': 'Expand to whole diagrams', 'diagram_snap_hint': 'Includes every diagram touching the selection.',
    'diagram_vectors_only': 'Vector paths only', 'diagram_vectors_only_hint': 'Leave out text and images.',
    'images_manager_title': 'Images in this document',
    'images_manager_hint': 'Replacing an image updates every place it appears.',
    'images_save_all': 'Save All Images (ZIP)…', 'images_none': 'This document contains no images.',
    'images_transparent': 'transparent', 'images_placements': '{} placement(s) on pages {}',
    'images_replace_everywhere': 'Replace Everywhere…',
    'status_image_replaced': 'Image replaced on {} page(s).', 'status_images_saved': 'Saved {} image(s).',

    # Authoring
    'menu_compose': 'Compose Document…', 'menu_rich_text': 'Formatted Text Box…', 'menu_watermark': 'Watermark…',
    'menu_mail_merge': 'Mail Merge from CSV…',
    'compose_content': 'Content', 'compose_hint': 'Text flows across as many pages as needed. '
                                                   'A line with \\pagebreak starts a new page.',
    'compose_layout': 'Layout', 'compose_toc': 'Table of contents',
    'compose_toc_hint': 'Linked entries for headings with stable page numbers; headings also become bookmarks.',
    'compose_toc_title': 'Contents', 'compose_page_numbers': 'Page numbers', 'compose_css': 'Extra CSS (optional)',
    'status_composed': 'Created a {}-page document.',
    'rich_text_hint': 'Enter the position below, or select an area on the page first.',
    'rich_text_hint_selection': 'The text is fitted into the selected area.',
    'status_rich_text_added': 'Formatted text added.',
    'watermark_text': 'Text', 'watermark_hint': 'Any angle; tiling repeats the text across the page.',
    'watermark_angle': 'Angle (°, counter-clockwise)', 'watermark_tile': 'Repeat across the page',
    'watermark_behind': 'Behind the page content', 'watermark_behind_hint': 'May be hidden by opaque backgrounds.',
    'merge_template': 'Template (this document)',
    'merge_hint': 'CSV columns fill form fields with the same name and replace {{column}} text placeholders.',
    'merge_fields': 'Form fields', 'merge_placeholders': 'Text placeholders', 'merge_data': 'Data',
    'merge_csv': 'CSV file', 'merge_matched': 'Records', 'merge_matched_value': '{} record(s); matched: {}',
    'merge_no_match': 'No CSV column matches a field or placeholder in this document.',
    'merge_combined': 'One combined document (new tab)', 'merge_separate': 'One file per record',
    'merge_filename': 'File name pattern ({n} or {column})', 'merge_flatten': 'Flatten form fields',
    'merge_flatten_hint': 'Makes filled values part of the page.', 'status_merged': 'Merged {} record(s).',

    # Signature internals and repaired files
    'pkcs7_subfilter': 'Signature format', 'pkcs7_digest': 'Digest algorithm',
    'pkcs7_algorithm': 'Signature algorithm', 'pkcs7_byte_range': 'Signed byte range',
    'pkcs7_timestamp': 'Trusted timestamp', 'pkcs7_reason': 'Reason', 'pkcs7_location': 'Location',
    'pkcs7_certificate': 'Certificate {}', 'pkcs7_save_container': 'Save PKCS#7 (.p7s)…',
    'pkcs7_save_chain': 'Save Certificates (PEM)…',
    'repaired_notice': 'This file was damaged and has been repaired in memory.',
    'repaired_save_copy': 'Save Repaired Copy',

    # Recovery
    'recovery_title': 'Recover unsaved documents?',
    'recovery_body': 'pdfLX closed unexpectedly. These documents had unsaved changes:\n{}',
    'recovery_recover': 'Recover', 'recovery_discard': 'Discard', 'recovery_later': 'Ask Next Time',

    # Batch
    'menu_batch': 'Batch Process Files…', 'batch_run': 'Run…', 'batch_files': 'Files',
    'batch_files_hint': 'Originals are never changed; results are written to a folder you choose.',
    'batch_choose': 'Input files', 'batch_operation': 'Operation', 'batch_text': 'Text',
    'batch_optimize': 'Reduce file size', 'batch_sanitize': 'Sanitize', 'batch_protect': 'Add password protection',
    'batch_watermark': 'Add watermark', 'batch_bates': 'Bates numbering (continuous across files)',
    'batch_rasterize': 'Flatten to images', 'batch_gray': 'Convert to grayscale',
    'batch_to_pdf': 'Convert to PDF', 'batch_markdown': 'Export Markdown text',
    'batch_failed': '{} file(s) failed.', 'security_owner_required': 'Enter an owner password.',

    # Viewer
    'menu_page_layout': 'Page layout', 'layout_page': 'Single page', 'layout_continuous': 'Continuous',
    'layout_spread': 'Two pages', 'layout_book': 'Book (cover on its own)',
    'menu_presentation': 'Presentation', 'presentation_hint': 'Arrow keys change slides. Press Esc to leave.',
    'menu_side_viewer': 'Side-by-Side Viewer', 'side_viewer_title': 'Side-by-side',
    'side_viewer_refresh': 'Refresh', 'menu_measure': 'Measure', 'menu_measure_settings': 'Measurement Scale…',
    'measure_hint': 'Drag to measure a distance; hold Ctrl for an area. Scale: {}.',
    'measure_area': 'area', 'measure_perimeter': 'perimeter', 'measure_keep': 'Keep as Annotation',
    'measure_units': 'Units and scale', 'measure_units_hint': 'Use a scale for drawings, e.g. 100 for 1:100.',
    'measure_unit': 'Unit', 'measure_scale': 'Scale factor',
    'measure_scale_hint': 'Real-world units per unit on paper.', 'status_measure_saved': 'Measurement scale saved.',

    # Advanced structure
    'menu_einvoice': 'Attach E-Invoice (Factur-X / ZUGFeRD)…', 'menu_portfolio': 'Create Portfolio…',
    'menu_object_inspector': 'PDF Object Inspector…',
    'einvoice_title': 'Invoice XML', 'einvoice_hint': 'Embeds the UN/CEFACT Cross Industry Invoice as an '
                                                      'associated file and adds Factur-X metadata.',
    'einvoice_xml': 'Invoice XML file', 'einvoice_profile': 'Profile', 'einvoice_filename': 'Attachment name',
    'einvoice_warning': 'Factur-X and ZUGFeRD also require the PDF itself to be PDF/A-3 conformant. pdfLX does '
                        'not convert or validate PDF/A; check the result with a Factur-X validator before sending.',
    'einvoice_existing': 'Existing invoice', 'einvoice_existing_hint': 'Already embedded in this document.',
    'status_einvoice_attached': 'Invoice XML attached.',
    'portfolio_title': 'Files', 'portfolio_hint': 'Creates a PDF that carries the files, with a cover page.',
    'portfolio_files': 'Files to include', 'portfolio_default_title': 'Portfolio',
    'status_portfolio_created': 'Portfolio with {} file(s) created.',
    'objects_warning': 'Advanced: editing raw objects can make the document unreadable. Changes can be undone.',
    'objects_read_only': 'Switch to Edit mode to change objects.',
    'objects_find': 'Find objects', 'objects_query': 'Object number, /Type, or text',
    'objects_selected': 'Object', 'objects_object': 'Object {} 0 R', 'objects_save': 'Save Object',
    'objects_binary_stream': 'This object has a binary stream; only its dictionary can be edited here.',
    'status_object_saved': 'Object {} saved.',

    # Drawing
    'menu_draw_shape': 'Draw Shape…', 'menu_node_editor': 'Edit Drawing Nodes…',
    'shape_kind': 'Shape', 'shape_star': 'Star', 'shape_polygon': 'Regular polygon', 'shape_triangle': 'Triangle',
    'shape_arrow': 'Block arrow', 'shape_sector': 'Sector (pie slice)', 'shape_arc': 'Arc',
    'shape_rounded_rectangle': 'Rounded rectangle', 'shape_points': 'Points / sides',
    'shape_inner': 'Inner size or corner radius (%)', 'shape_start_angle': 'Start angle (°)',
    'shape_sweep': 'Sweep (°)', 'status_shape_added': 'Shape added.',
    'nodes_need_stroke': 'Select a pen drawing first (Edit mode, Select tool).',
    'nodes_rotated': 'Reset the drawing\'s rotation before editing its nodes.',
    'nodes_title': 'Path nodes', 'nodes_hint': 'On the page: drag a node to move it, Ctrl+click the path to '
                                               'insert a node, Shift+click a node to delete it. Esc finishes.',
    'nodes_count': 'Nodes', 'nodes_simplify_tolerance': 'Simplify tolerance (pt)',
    'nodes_smooth_iterations': 'Smoothing passes', 'nodes_simplify': 'Simplify', 'nodes_smooth': 'Smooth',
    'nodes_edit_on_page': 'Edit on Page', 'nodes_status': 'Editing nodes. Press Esc or choose another tool to finish.',

    'menu_enter_edit_mode': 'Switch to Edit Mode to Enable All Tools',

    # Form scripts, behaviour, buttons, and data
    'menu_form_scripts': 'Run Form Scripts (Calculations and Validation)',
    'menu_form_import': 'Import Form Data…', 'menu_form_export': 'Export Form Data…', 'btn_import': 'Import',
    'form_scripts_disabled': 'Form scripts are turned off (main menu > Run Form Scripts).',
    'form_script_ran': 'Button script ran.', 'form_pick_date': 'Pick a date',
    'form_value_rejected': 'Value not accepted',
    'button_kind': 'Button', 'button_action': 'Button action', 'button_action_reset': 'Reset form',
    'button_action_goto': 'Go to page', 'button_action_submit': 'Submit form', 'button_action_url': 'Open web address',
    'button_action_print': 'Print document', 'button_action_javascript': 'Run JavaScript',
    'button_destination_page': 'Destination page', 'button_url': 'Address (https:// or mailto:)',
    'button_submit_format': 'Submission format', 'button_script': 'Script',
    'button_no_action': 'No supported button action. Use Properties to choose one.',
    'button_submit_title': 'Submit form',
    'button_submit_body': 'This button submits the form to {} when the PDF is filled in a reader that '
                          'supports submission. pdfLX does not send data over the network; you can export '
                          'the form data instead.',
    'button_submit_export': 'Export Form Data…',
    'behaviour_tab': 'Format & Calculation', 'behaviour_format': 'Format',
    'behaviour_format_none': 'None', 'behaviour_format_number': 'Number', 'behaviour_format_percent': 'Percentage',
    'behaviour_format_date': 'Date', 'behaviour_format_time': 'Time', 'behaviour_format_special': 'Special',
    'behaviour_decimals': 'Decimal places', 'behaviour_separator': 'Separator style',
    'behaviour_negative': 'Negative numbers', 'behaviour_currency': 'Currency symbol',
    'behaviour_currency_before': 'Symbol before the number', 'behaviour_date_format': 'Date format',
    'behaviour_time_format': 'Time format', 'behaviour_special': 'Special format',
    'behaviour_special_0': 'ZIP code', 'behaviour_special_1': 'ZIP+4', 'behaviour_special_2': 'Phone number',
    'behaviour_special_3': 'Social Security number',
    'behaviour_minimum': 'Value must be at least', 'behaviour_minimum_value': 'Minimum',
    'behaviour_maximum': 'Value must be at most', 'behaviour_maximum_value': 'Maximum',
    'behaviour_calculate': 'Calculate', 'behaviour_calc_none': 'Not calculated', 'behaviour_calc_SUM': 'Sum of',
    'behaviour_calc_AVG': 'Average of', 'behaviour_calc_PRD': 'Product of', 'behaviour_calc_MIN': 'Minimum of',
    'behaviour_calc_MAX': 'Maximum of', 'behaviour_calc_custom': 'Custom script',
    'behaviour_sources': 'Fields', 'behaviour_no_sources': 'Create other fields first.',
    'behaviour_custom': 'Calculation script',
    'behaviour_note': 'Saved as standard Acrobat form scripts, so formatting, validation, and calculations '
                      'also work in other PDF readers.',
    'forms_calc_order': 'Calculation order',
    'forms_calc_order_hint': 'Fields are recalculated in this order; put a field before the fields that use it.',
    'forms_calc_none': 'No calculated fields.',
    'formdata_export_title': 'Field values', 'formdata_export_hint': 'XFDF and FDF are the standard PDF formats; '
                                                                        'JSON and CSV suit spreadsheets and scripts.',
    'formdata_fields': 'Fields', 'formdata_import_title': 'Field values',
    'formdata_import_hint': 'Values are matched to fields by their full names (parent.child).',
    'formdata_file': 'Data file', 'formdata_files': 'Form data (FDF, XFDF, JSON, CSV)', 'formdata_match': 'Match',
    'formdata_match_value': '{}: {} of {} value(s) match this form.', 'formdata_unmatched': 'Not found: {}.',
    'formdata_csv_row': 'CSV row', 'status_formdata_exported': 'Exported {} field value(s).',
    'status_formdata_imported': 'Filled {} field(s); {} name(s) did not match.',

    # Existing keys that previously fell back to the key name
    'delete_page_title': 'Delete Page', 'err_image_delete_title': 'Could Not Delete Image',
    'err_image_delete_msg': 'The image could not be deleted.', 'image_delete_confirm_title': 'Delete Image?',
    'image_delete_confirm_msg': 'Delete the selected image?',
    'dbg_creating_drag_command': 'Creating drag command', 'dbg_format_change_saved': 'Format change saved',
    'dbg_tool_changed': 'Tool changed: {}',
    # Shared dialog and inspector layout.
    'props_position': 'Position',
    'props_x': 'Horizontal',
    'props_y': 'Vertical',
    'props_size': 'Size & rotation',
    'props_rotation': 'Rotation',
    'stamp_place': 'Place on Page',
    'stamp_templates': 'Templates',
    'stamp_save_template': 'Save as Template',
    'stamp_save_template_body': 'Saved templates appear in the gallery every time you add a stamp.',
    'stamp_template_name': 'Template name',
    'stamp_remove_template': 'Remove this saved template',
    'stamp_fields_hint': 'Use + to insert the date, time or author; they are filled in when the stamp is placed.',
    'stamp_details': 'Details line (optional)',
    'stamp_insert_field': 'Insert field',
    'stamp_field_date': 'Date',
    'stamp_field_time': 'Time',
    'stamp_field_datetime': 'Date and time',
    'stamp_field_author': 'Author name',
    'stamp_text_size': 'Text size',
    'stamp_text_size_hint': 'Largest size; long text shrinks to fit',
    'stamp_color_red': 'Red', 'stamp_color_green': 'Green', 'stamp_color_blue': 'Blue',
    'stamp_color_orange': 'Orange', 'stamp_color_purple': 'Purple', 'stamp_color_gray': 'Gray',
    'stamp_color_black': 'Black', 'stamp_color_custom': 'Custom color',
    'stamp_border_none': 'None', 'stamp_border_solid': 'Solid', 'stamp_border_double': 'Double',
    'stamp_border_dashed': 'Dashed',
    'stamp_fill': 'Tinted background',
    'stamp_fill_hint': 'A light wash of the stamp color behind the text',
    'stamp_width': 'Width',
    'stamp_tilt': 'Tilt',
    'stamp_author_name': 'Name shown as the stamp author',
    'stamp_dimensions': '{} × {} pt',
    'stamp_place_hint': 'After clicking Place on Page, click anywhere on the page to drop the stamp. Press Escape to stop.',
    'stamp_edit_hint': 'Changes replace the selected stamp in the same position.',
    'stamp_tpl_approved': 'Approved', 'stamp_tpl_not_approved': 'Not approved', 'stamp_tpl_draft': 'Draft',
    'stamp_tpl_confidential': 'Confidential', 'stamp_tpl_final': 'Final', 'stamp_tpl_for_comment': 'For comment',
    'stamp_tpl_reviewed': 'Reviewed', 'stamp_tpl_received': 'Received', 'stamp_tpl_paid': 'Paid',
    'stamp_tpl_completed': 'Completed', 'stamp_tpl_urgent': 'Urgent', 'stamp_tpl_void': 'Void',
    'stamp_tpl_copy': 'Copy', 'stamp_tpl_sign_here': 'Sign here',
    'props_width': 'Width',
    'redact_section_search': 'Search',
    'props_height': 'Height',
    'props_font_size': 'Font size',
    'props_stroke_width': 'Stroke width',
    'props_text': 'Text',
    'props_style': 'Style',
    'props_appearance': 'Appearance',
    'props_stroke_color': 'Stroke color',
    'image_tools_title': 'Image',
    'image_tools_close': 'Close image tools',
    'image_rotate_left': 'Rotate left 90°',
    'image_rotate_right': 'Rotate right 90°',
    'image_flip_horizontal': 'Flip horizontally',
    'image_flip_vertical': 'Flip vertically',
    'image_restore_ratio': 'Restore original proportions',
    'image_reset': 'Reset crop and appearance',
    'image_replace': 'Replace image',
    'image_replace_short': 'Replace',
    'image_section_appearance': 'Appearance',
    'image_section_border': 'Border',
    'image_section_effects': 'Effects',
    'image_opacity': 'Opacity',
    'image_tilt': 'Tilt',
    'image_corners': 'Corner radius',
    'image_border_width': 'Width',
    'image_border_color': 'Color',
    'image_crop': 'Crop',
    'image_crop_active': 'Edges trimmed',
    'image_crop_left': 'Left',
    'image_crop_top': 'Top',
    'image_crop_right': 'Right',
    'image_crop_bottom': 'Bottom',
    'image_shadow': 'Drop shadow',
    'image_shadow_distance': 'Distance',
    'image_shadow_strength': 'Strength',
    'print_title': 'Print',
    'print_action': 'Print',
    'print_save_pdf': 'Save PDF',
    'print_group_printer': 'Printer',
    'print_printer': 'Printer',
    'print_searching': 'Looking for printers…',
    'print_default': 'Default printer',
    'print_output_file': 'Output file',
    'print_copies': 'Copies',
    'print_collate': 'Collate',
    'print_collate_hint': 'Print complete copies one after another',
    'print_group_pages': 'Pages',
    'print_reverse': 'Reverse order',
    'print_group_layout': 'Layout',
    'print_paper': 'Paper size',
    'print_orientation': 'Orientation',
    'print_orientation_auto': 'Automatic',
    'print_orientation_portrait': 'Portrait',
    'print_orientation_landscape': 'Landscape',
    'print_scaling': 'Scaling',
    'print_scale_fit': 'Fit to printable area',
    'print_scale_shrink': 'Shrink oversized pages',
    'print_scale_actual': 'Actual size',
    'print_group_output': 'Output',
    'print_color': 'Color',
    'print_color_color': 'Color',
    'print_color_gray': 'Grayscale',
    'print_duplex': 'Two-sided',
    'print_duplex_off': 'Off',
    'print_duplex_long': 'Flip on long edge',
    'print_duplex_short': 'Flip on short edge',
    'print_system_dialog': 'System print dialog',
    'print_system_dialog_hint': 'Printer-specific options such as trays and quality',
    'print_prev_page': 'Previous page',
    'print_next_page': 'Next page',
    'print_page_of': 'Page {} of {}',
    'print_summary': '{} pages · {} sheets of paper',
    'print_no_pages': 'Enter a valid page range',
    'pdf_password_open': 'Unlock',
    'metadata_group': 'Document information',
    'bookmark_new': 'New bookmark',
}

# Menu group labels, translated so the restructured menu reads naturally.
MENU_TRANSLATIONS = {
    'tr': {'menu_group_document': 'Belge', 'menu_group_pages': 'Sayfalar', 'menu_group_annotate': 'Açıklama',
           'menu_group_insert': 'Ekle ve Formlar', 'menu_group_protect': 'Koruma', 'menu_group_tools': 'Araçlar',
           'menu_view': 'Görünüm', 'menu_main_tip': 'Ana menü'},
    'fr': {'menu_group_document': 'Document', 'menu_group_pages': 'Pages', 'menu_group_annotate': 'Annoter',
           'menu_group_insert': 'Insérer et formulaires', 'menu_group_protect': 'Protéger',
           'menu_group_tools': 'Outils', 'menu_view': 'Affichage', 'menu_main_tip': 'Menu principal'},
    'de': {'menu_group_document': 'Dokument', 'menu_group_pages': 'Seiten', 'menu_group_annotate': 'Kommentieren',
           'menu_group_insert': 'Einfügen und Formulare', 'menu_group_protect': 'Schützen',
           'menu_group_tools': 'Werkzeuge', 'menu_view': 'Ansicht', 'menu_main_tip': 'Hauptmenü'},
    'es': {'menu_group_document': 'Documento', 'menu_group_pages': 'Páginas', 'menu_group_annotate': 'Anotar',
           'menu_group_insert': 'Insertar y formularios', 'menu_group_protect': 'Proteger',
           'menu_group_tools': 'Herramientas', 'menu_view': 'Ver', 'menu_main_tip': 'Menú principal'},
    'it': {'menu_group_document': 'Documento', 'menu_group_pages': 'Pagine', 'menu_group_annotate': 'Annota',
           'menu_group_insert': 'Inserisci e moduli', 'menu_group_protect': 'Proteggi',
           'menu_group_tools': 'Strumenti', 'menu_view': 'Visualizza', 'menu_main_tip': 'Menu principale'},
    'ru': {'menu_group_document': 'Документ', 'menu_group_pages': 'Страницы', 'menu_group_annotate': 'Комментарии',
           'menu_group_insert': 'Вставка и формы', 'menu_group_protect': 'Защита',
           'menu_group_tools': 'Инструменты', 'menu_view': 'Вид', 'menu_main_tip': 'Главное меню'},
}
