# -*- coding: utf-8 -*-
"""English strings for document operations (pdflx.features / pdflx.dialogs).

Other languages fall back to English for these keys until translated; the
main menu group labels are translated below.
"""

STRINGS_EN = {
    # Generic
    'btn_add': 'Add', 'btn_choose': 'Choose…', 'btn_collate': 'Collate', 'btn_create': 'Create',
    'btn_dismiss': 'Dismiss', 'btn_export': 'Export…', 'btn_extract': 'Extract', 'btn_find_remove': 'Find and Remove',
    'btn_flatten': 'Flatten', 'btn_insert': 'Insert', 'btn_scan': 'Scan', 'btn_split': 'Split…',
    'yes': 'Yes', 'no': 'No', 'dpi': 'Resolution (DPI)', 'margin_pt': 'Margin (pt)',
    'keep_proportions': 'Keep proportions', 'paper_size': 'Paper size', 'paper_landscape': 'Landscape',
    'untitled_document': 'Untitled Document', 'output': 'Output', 'output_destination': 'Destination',
    'output_new_tab': 'Open in a new tab', 'output_file': 'Save as a file', 'output_zip': 'ZIP archive',
    'output_folder': 'Folder', 'saved_to': 'Saved to {}', 'file_none_selected': 'No file selected',
    'preview_refresh': 'Refresh preview', 'progress_working': 'Working…', 'progress_count': '{} of {}',
    'progress_cancelling': 'Cancelling…', 'progress_cancelled': 'The operation was cancelled.',
    'range_pages': 'Pages', 'range_all': 'All', 'range_current': 'Current', 'range_selected': '{} page(s) selected',
    'filter_documents': 'Documents and images', 'filter_convertible': 'XPS, EPUB, MOBI, FB2, CBZ, SVG, text, images',
    'filter_supported': 'All supported files',
    'pos_after_current': 'After the current page', 'pos_before_current': 'Before the current page',
    'pos_start': 'At the beginning', 'pos_end': 'At the end',
    'colorspace_gray': 'Grayscale', 'colorspace_rgb': 'RGB', 'colorspace_cmyk': 'CMYK',

    # Errors
    'err_no_doc_to_save': 'There is no document to save.',
    'err_incremental_unavailable': 'Changes can only be appended to the unencrypted, unrepaired PDF file this '
                                   'document was opened from.',
    'err_cannot_delete_all_pages': 'A document must keep at least one page.',
    'err_choose_file': 'Choose a file first.', 'err_edit_not_allowed': 'Switch to Edit mode to change this document.',
    'err_form_values': 'Some form values are invalid. Correct them first.',
    'err_insert_encrypted': 'Password-protected files cannot be used here. Remove the password first.',
    'err_need_two_pages': 'This needs a document with at least two pages.',
    'err_no_annotations': 'This document has no annotations.', 'err_open_file': 'Could not open {}: {}',
    'err_overlay_same_file': 'Choose a different PDF for the overlay.',
    'err_overwrite_open_file': 'Choose a different file name; the open document cannot be overwritten here.',
    'err_owner_required': 'Open the document with its owner password to change security.',
    'err_pages_have_editor_objects': 'Pages {} contain editable objects added in pdfLX. Flatten or remove them '
                                     'before changing page geometry so they are not misplaced.',
    'err_pyhanko_missing': 'Signature verification requires pyHanko. Install the application dependencies.',

    # Menus
    'menu_main_tip': 'Main menu', 'menu_group_document': 'Document', 'menu_group_pages': 'Pages',
    'menu_group_annotate': 'Annotate & Review', 'menu_group_insert': 'Insert and Forms', 'menu_group_protect': 'Protect',
    'menu_group_tools': 'Tools', 'menu_view': 'View', 'menu_reader_mode': 'Reading colors',
    'reader_mode_normal': 'Original colors', 'reader_mode_night': 'Night', 'reader_mode_sepia': 'Sepia',
    'reader_mode_contrast': 'High contrast',
    'menu_open_other_format': 'Open Other Format…', 'menu_images_to_pdf': 'Create PDF from Images…',
    'menu_save_incremental': 'Save Incrementally', 'menu_document_info': 'Document Information…',
    'menu_viewer_settings': 'Viewer Settings…', 'menu_generate_bookmarks': 'Generate Bookmarks from Headings…',
    'menu_links': 'Links…', 'menu_attachments': 'Attachments…', 'menu_layers': 'Layers…',
    'menu_insert_pages': 'Insert Pages from File…', 'menu_extract_pages': 'Extract Pages…',
    'menu_split_document': 'Split Document…', 'menu_reverse_pages': 'Reverse Page Order',
    'menu_collate_pages': 'Collate Scanned Pages…', 'menu_remove_blank_pages': 'Remove Blank Pages…',
    'menu_remove_rotation': 'Make Rotation Permanent…', 'menu_resize_pages': 'Resize Pages…',
    'menu_page_boxes': 'Page Boxes…', 'menu_nup_pages': 'N-Up and Booklet…',
    'menu_headers_footers': 'Headers, Footers and Bates…', 'menu_overlay_pages': 'Background and Overlay…',
    'menu_page_labels': 'Page Labels…', 'menu_add_markup': 'Shapes, Text Boxes and Attachments…',
    'menu_export_annotations': 'Export Annotations…', 'menu_import_annotations': 'Import Annotations…',
    'menu_comment_summary': 'Comment Summary…', 'menu_flatten_annotations': 'Flatten Annotations…',
    'menu_security': 'Password and Permissions…', 'menu_verify_signatures': 'Verify Signatures…',
    'menu_sanitize': 'Sanitize Document…', 'menu_hidden_text': 'Find Hidden Text…',
    'menu_rasterize': 'Flatten Pages to Images…', 'menu_advanced_search': 'Advanced Search…',
    'menu_compare': 'Compare Documents…', 'menu_text_style': 'Text Properties…',
    'menu_snapshot': 'Copy Selection as Image', 'menu_ocr': 'Recognize Text (OCR)…',
    'menu_optimize': 'Reduce File Size…', 'menu_recolor': 'Convert Colors…',
    'menu_export_structured': 'Structured Text…', 'menu_export_images': 'Pages as Images…',
    'menu_export_tables': 'Tables as Markdown or JSON…',

    # Signed documents
    'signed_save_title': 'This PDF is digitally signed',
    'signed_save_body': 'Signed fields: {}. Rewriting the file invalidates these signatures.',
    'signed_save_append_hint': 'Append Changes adds your edits as a new revision and keeps the signed revision '
                               'intact. Verifiers will still report that the document changed after signing.',
    'signed_save_copy': 'Save as Copy…', 'signed_save_append': 'Append Changes',
    'signed_save_rewrite': 'Rewrite File',

    # Insert / extract / split
    'insert_source': 'Source', 'insert_source_hint': 'PDF, XPS, EPUB, images, and other supported files.',
    'insert_file': 'File', 'insert_source_pages': 'Pages to insert (empty = all)', 'insert_position': 'Position',
    'extract_delete_after': 'Delete extracted pages from this document',
    'extract_delete_hint': 'Available in Edit mode. Undo restores them.',
    'split_method': 'Split method', 'split_every': 'Every N pages', 'split_ranges': 'Custom ranges',
    'split_bookmarks': 'At top-level bookmarks', 'split_single': 'One file per page',
    'split_pages_per_file': 'Pages per file', 'split_range_groups': 'Ranges, separated by ; (e.g. 1-3; 4-10)',
    'split_result': 'Result', 'split_preview': '{} file(s)', 'split_choose_folder': 'Choose a folder for the parts',

    # Order / blanks / geometry
    'collate_title': 'Interleave front and back scans',
    'collate_hint': 'For a stack scanned as all fronts followed by all backs.',
    'collate_fronts': 'Number of front pages', 'collate_backs_reversed': 'Backs were scanned in reverse order',
    'collate_result': 'New order',
    'blank_title': 'Detect blank pages', 'blank_hint': 'Pages with annotations or form fields are never removed.',
    'blank_threshold': 'Blank when this share is background (%)',
    'blank_threshold_hint': 'Lower values also remove pages with specks or scan noise.',
    'blank_none_found': 'No blank pages were found.',
    'rotation_title': 'Make page rotation permanent',
    'rotation_hint': 'Rewrites rotated pages so they read upright with a rotation of 0°. Useful for tools that '
                     'ignore the rotation setting.',
    'rotation_none': 'None of the selected pages is rotated.',
    'resize_title': 'Place pages on a uniform paper size',
    'resize_hint': 'Creates a new document. Links and annotations on resized pages are not carried over.',
    'nup_layout': 'Layout', 'nup_hint': 'Creates a new document for printing.', 'nup_sheet': 'Sheet',
    'nup_2': '2 pages per sheet', 'nup_4': '4 pages per sheet', 'nup_6': '6 pages per sheet',
    'nup_9': '9 pages per sheet', 'nup_16': '16 pages per sheet',
    'nup_booklet': 'Booklet (saddle stitch, print double-sided on the short edge)',
    'nup_borders': 'Draw page borders', 'nup_columns_first': 'Fill columns first',
    'overlay_source': 'Overlay document', 'overlay_hint': 'Use letterhead or stationery behind pages, or a '
                                                           'form or mark in front of them.',
    'overlay_file': 'PDF file', 'overlay_source_page': 'Page of the overlay document', 'overlay_placement': 'Placement',
    'overlay_behind': 'Behind the content (background)', 'overlay_front': 'In front of the content (overlay)',

    # Headers and footers
    'hf_text': 'Text', 'hf_placeholders': 'Placeholders: {page}, {total}, {bates}, {file}, {date}',
    'hf_top_left': 'Top left', 'hf_top_center': 'Top center', 'hf_top_right': 'Top right',
    'hf_bottom_left': 'Bottom left', 'hf_bottom_center': 'Bottom center', 'hf_bottom_right': 'Bottom right',
    'hf_style': 'Style', 'hf_bates': 'Bates numbering', 'hf_bates_hint': 'Insert the number with {bates}.',
    'hf_bates_enable': 'Enable Bates numbering', 'hf_bates_prefix': 'Prefix', 'hf_bates_start': 'Start number',
    'hf_bates_digits': 'Digits', 'hf_bates_suffix': 'Suffix',

    # Labels and boxes
    'labels_rules': 'Numbering rules',
    'labels_hint': 'Logical page numbers shown by PDF readers, e.g. i–iv for front matter, then 1, 2, 3.',
    'labels_add_rule': 'Add rule', 'labels_remove_rule': 'Remove rule', 'labels_preview': 'Preview',
    'labels_start_page': 'First physical page of this rule', 'labels_prefix': 'Prefix',
    'labels_first_number': 'Number of the first page', 'labels_from_page': 'From page',
    'labels_from_number': 'start at',
    'label_style_D': '1, 2, 3', 'label_style_r': 'i, ii, iii', 'label_style_R': 'I, II, III',
    'label_style_a': 'a, b, c', 'label_style_A': 'A, B, C', 'label_style_none': 'Prefix only',
    'boxes_current': 'Current boxes (page {})', 'boxes_hint': 'Values in points. Bleed, trim, and art boxes are '
                                                               'used by print production workflows.',
    'boxes_set_inset': 'Inset from the crop box',
    'box_mediabox': 'Media box', 'box_cropbox': 'Crop box', 'box_bleedbox': 'Bleed box', 'box_trimbox': 'Trim box',
    'box_artbox': 'Art box',
    'box_trimbox_hint': 'The finished page size after trimming.',
    'box_bleedbox_hint': 'The area to which content may extend for trimming tolerance.',
    'box_artbox_hint': 'The meaningful content area.',

    # Annotations
    'markup_type': 'Annotation', 'markup_text': 'Text', 'markup_area': 'Position on the page',
    'markup_hint_selection': 'The annotation uses the area selected on the page.',
    'markup_hint_no_selection': 'Tip: select an area on the page first, or enter its position below.',
    'markup_rectangle': 'Rectangle', 'markup_ellipse': 'Ellipse', 'markup_line': 'Line', 'markup_arrow': 'Arrow',
    'markup_double_arrow': 'Double arrow', 'markup_textbox': 'Text box (typewriter)', 'markup_callout': 'Callout',
    'markup_caret': 'Insertion mark', 'markup_attachment': 'File attachment',
    'markup_attachment_file': 'File to attach', 'markup_style': 'Style', 'markup_stroke': 'Line and text color',
    'markup_fill_enable': 'Fill', 'markup_fill': 'Fill color', 'markup_line_width': 'Line width',
    'markup_dashed': 'Dashed line',
    'flatten_annotations_body': 'Burn {} annotation(s) into the page content? They will no longer be editable '
                                'as comments. Form fields are kept. You can undo this until you close the document.',
    'summary_preview': 'Preview',

    # Security
    'security_current': 'Current protection', 'security_encryption': 'Encryption', 'security_none': 'None',
    'security_allowed': 'Allowed', 'security_passwords': 'Passwords',
    'security_passwords_hint': 'The open password is optional. The owner password is required to enforce '
                               'permissions.',
    'security_open_password': 'Password to open', 'security_owner_password': 'Owner password',
    'security_method': 'Encryption', 'security_permissions': 'Permissions',
    'security_permissions_hint': 'Reader software decides how strictly permissions are enforced.',
    'security_remove': 'Remove protection',
    'security_remove_hint': 'Saves an unencrypted copy. Requires the owner password.',
    'security_remove_button': 'Save Unprotected Copy…', 'security_save_protected': 'Save Protected Copy…',
    'perm_print': 'Print', 'perm_print_hq': 'Print in high quality', 'perm_modify': 'Change content',
    'perm_copy': 'Copy text and images', 'perm_accessibility': 'Extract text for accessibility',
    'perm_annotate': 'Add and change comments', 'perm_form': 'Fill in form fields',
    'perm_assemble': 'Insert, delete, and rotate pages',
    'sanitize_remove': 'Remove', 'sanitize_hint': 'Creates a cleaned copy; the open document is not changed.',
    'sanitize_note': 'Images partly covered by redactions are blanked pixel by pixel. Sanitization does not '
                     'remove information that is visible on the page; use Redact for that.',
    'sanitize_save': 'Save Sanitized Copy…',
    'scrub_metadata': 'Document information (title, author, …)', 'scrub_xml_metadata': 'XMP metadata',
    'scrub_javascript': 'JavaScript', 'scrub_embedded_files': 'Embedded files',
    'scrub_attached_files': 'File-attachment annotations', 'scrub_remove_links': 'Links',
    'scrub_thumbnails': 'Embedded page thumbnails', 'scrub_reset_fields': 'Reset form fields to their defaults',
    'scrub_reset_responses': 'Annotation replies', 'scrub_hidden_text': 'Hidden (invisible) text',
    'scrub_redactions': 'Apply pending redactions', 'scrub_clean_pages': 'Clean and compact page content',
    'hidden_title': 'Text a reader would not see',
    'hidden_hint': 'Invisible, white, transparent, tiny, or off-page text. White text may be legitimate on dark '
                   'backgrounds; review each result.',
    'hidden_summary': 'Result', 'hidden_not_scanned': 'Not scanned yet.', 'hidden_found': '{} item(s) found.',
    'hidden_none': 'No hidden text was found.',
    'hidden_reason_invisible': 'Invisible', 'hidden_reason_white': 'White', 'hidden_reason_transparent': 'Transparent',
    'hidden_reason_tiny': 'Tiny', 'hidden_reason_off-page': 'Off the page',
    'rasterize_title': 'Replace pages with images',
    'rasterize_hint': 'Creates a new document. Text, links, comments, and form fields on these pages become part '
                      'of a picture and can no longer be selected or searched.',
    'rasterize_gray': 'Grayscale',

    # Signature verification
    'verify_hint': 'Checks the file on disk: integrity, signer certificate, trust, and changes after signing.',
    'verify_hint_modified': 'The document has unsaved changes; the saved file on disk is verified.',
    'verify_trust': 'Trust', 'verify_system_roots': 'Trust system certificate authorities',
    'verify_extra_roots': 'Additional trusted certificates',
    'verify_extra_roots_hint': 'PEM or DER files, for example your organization\'s root certificate.',
    'verify_results': 'Signatures', 'verify_run': 'Verify Again', 'verify_running': 'Verifying…',
    'verify_none': 'This document has no digital signatures.', 'verify_unnamed': 'Unnamed signature',
    'verify_status_valid': 'Valid: unchanged since signing, signer trusted.',
    'verify_status_untrusted': 'Intact, but the signer is not trusted.',
    'verify_status_modified': 'Intact, but the document changed after signing.',
    'verify_status_invalid': 'Invalid: the signed content was altered or cannot be verified.',
    'verify_signer': 'Signer', 'verify_issuer': 'Issuer', 'verify_time': 'Signing time (claimed by signer)',
    'verify_intact': 'Signed data intact', 'verify_valid': 'Cryptographically valid', 'verify_trusted': 'Trusted',
    'verify_coverage': 'Coverage', 'verify_modifications': 'Changes after signing',

    # Conversion and optimization
    'images_source': 'Images', 'images_hint': 'One page per image; multi-page TIFFs add one page per frame.',
    'images_choose': 'Image files', 'images_layout': 'Page layout', 'images_native_size': 'Same as each image',
    'images_fit': 'Fit', 'images_fit_keep': 'Fit and keep proportions', 'images_fit_stretch': 'Stretch to fill',
    'optimize_images': 'Images', 'optimize_images_hint': 'Downsampling reduces the size of photos and scans.',
    'optimize_downsample': 'Downsample and recompress images', 'optimize_target_dpi': 'Target resolution (DPI)',
    'optimize_jpeg_quality': 'JPEG quality', 'optimize_gray_images': 'Convert images to grayscale',
    'optimize_other': 'Other', 'optimize_subset_fonts': 'Subset embedded fonts',
    'optimize_subset_hint': 'Keeps only the characters used. Text added later may need a different font.',
    'optimize_object_streams': 'Compress document structure',
    'optimize_remove_metadata': 'Remove metadata and thumbnails', 'optimize_result': 'Result',
    'optimize_size': 'Size', 'optimize_not_run': 'Press Analyze to estimate the result.',
    'optimize_size_result': '{} → {} ({:.0f}% smaller)', 'optimize_analyze': 'Analyze',
    'optimize_save': 'Save Optimized Copy…', 'optimize_save_now': 'Save Optimized Copy…',
    'optimize_running': 'Optimizing…',
    'recolor_title': 'Convert all colors', 'recolor_hint': 'Creates a new document with text, graphics, and images '
                                                           'converted to the chosen color space.',
    'recolor_target': 'Color space',
    'ocr_title': 'Make scanned pages searchable',
    'ocr_hint': 'Adds an invisible text layer and keeps the page appearance. Creates a new document.',
    'ocr_language': 'Language', 'ocr_extra_languages': 'Additional languages (e.g. deu+fra)',
    'ocr_skip_text_pages': 'Skip pages that already contain text', 'ocr_run': 'Recognize',
    'ocr_running': 'Recognizing text…', 'ocr_unavailable': 'OCR is not available',
    'ocr_nothing_done': 'All selected pages already contain text; nothing was recognized.',
    'export_image_format': 'Format', 'export_colorspace': 'Color space',
    'export_transparent': 'Transparent background', 'export_transparent_hint': 'PNG and PAM only.',
    'structured_title': 'Export text with structure',
    'structured_hint': 'Markdown recognizes headings by font size and includes detected tables.',
    'structured_format': 'Format', 'structured_reading_order': 'Sort into reading order',
    'structured_reading_order_hint': 'Orders text top-to-bottom, left-to-right. Turn off to keep the content '
                                     'stream order.',
    'tables_title': 'Detected tables', 'tables_hint': 'Tables are detected from ruling lines or text alignment.',
    'tables_csv_zip': 'CSV files (ZIP)', 'tables_strategy': 'Detection',
    'tables_strategy_lines': 'Ruling lines', 'tables_strategy_text': 'Text alignment',

    # Information and settings
    'info_overview': 'Overview', 'info_general': 'General', 'info_features': 'Contents and security',
    'info_file': 'File', 'info_file_size': 'File size', 'info_pages': 'Pages', 'info_page_sizes': 'Page sizes',
    'info_pdf_version': 'PDF version', 'info_producer': 'Producer', 'info_created': 'Created',
    'info_modified': 'Modified', 'info_encryption': 'Encryption', 'info_signed_fields': 'Signed fields',
    'info_form': 'Form fields', 'info_tagged': 'Tagged PDF', 'info_attachments': 'Attachments',
    'info_layers': 'Layers', 'info_javascript': 'JavaScript', 'info_xmp': 'XMP metadata',
    'info_fast_web': 'Fast web view', 'info_repaired': 'Repaired on opening', 'info_fonts': 'Fonts',
    'info_fonts_hint': 'Fonts that are not embedded are substituted by the reader.',
    'info_embedded': 'embedded', 'info_not_embedded': 'not embedded', 'info_subset': 'subset',
    'info_extract_font': 'Save font file…', 'info_statistics': 'Statistics',
    'info_compute_statistics': 'Count words, images, and links',
    'stat_pages': 'Pages', 'stat_words': 'Words', 'stat_characters': 'Characters (without spaces)',
    'stat_images': 'Image placements', 'stat_links': 'Links', 'stat_annotations': 'Annotations',
    'stat_form_fields': 'Form fields',
    'viewer_opening': 'When the document opens', 'viewer_hint': 'Stored in the PDF and honoured by most readers.',
    'viewer_page_mode': 'Show', 'viewer_page_layout': 'Page layout', 'viewer_window': 'Window',
    'viewer_document': 'Document', 'viewer_language': 'Language (e.g. en-US)',
    'viewer_need_appearances': 'Ask readers to regenerate form field appearances',
    'viewer_need_appearances_hint': 'Helps when field values look different in other readers.',
    'pagemode_UseNone': 'Page only', 'pagemode_UseOutlines': 'Bookmarks panel',
    'pagemode_UseThumbs': 'Thumbnails panel', 'pagemode_FullScreen': 'Full screen',
    'pagemode_UseOC': 'Layers panel', 'pagemode_UseAttachments': 'Attachments panel',
    'pagelayout_SinglePage': 'Single page', 'pagelayout_OneColumn': 'Continuous',
    'pagelayout_TwoColumnLeft': 'Two pages, continuous', 'pagelayout_TwoColumnRight': 'Two pages, continuous, with cover',
    'pagelayout_TwoPageLeft': 'Two pages', 'pagelayout_TwoPageRight': 'Two pages, with cover',
    'viewerpref_DisplayDocTitle': 'Show the document title instead of the file name',
    'viewerpref_FitWindow': 'Fit the window to the first page', 'viewerpref_CenterWindow': 'Center the window',
    'viewerpref_HideToolbar': 'Hide the reader toolbar', 'viewerpref_HideMenubar': 'Hide the reader menu bar',

    # Bookmarks
    'bookmark_indent': 'Make child of the previous bookmark', 'bookmark_outdent': 'Move one level up',
    'bookmark_move_up': 'Move up', 'bookmark_move_down': 'Move down',
    'bookmarks_replace': 'Apply', 'autotoc_settings': 'Detection',
    'autotoc_hint': 'Headings are recognized as text larger than the body text.',
    'autotoc_levels': 'Heading levels', 'autotoc_ratio': 'Minimum size relative to body text',
    'autotoc_mode': 'Existing bookmarks', 'autotoc_replace': 'Replace', 'autotoc_append': 'Keep and append',
    'autotoc_preview': 'Proposed bookmarks', 'autotoc_none': 'No headings were detected.',

    # Links, attachments, layers
    'links_add': 'Add link', 'links_add_hint': 'Select the clickable area on the page, then add the link.',
    'links_view_only': 'Switch to Edit mode to add or remove links.',
    'links_type': 'Link type', 'links_target': 'Web address', 'links_target_page': 'Target page',
    'links_named_action': 'Action', 'links_target_file': 'Target file', 'links_add_button': 'Add Link',
    'links_detect_urls': 'Link Web Addresses in Text', 'links_existing': 'Links', 'links_scope': 'Show',
    'links_scope_page': 'Current page', 'links_scope_all': 'All pages', 'links_none': 'No links.',
    'links_go': 'Go to page', 'links_delete': 'Delete link',
    'links_need_selection': 'Select the clickable area on the page first.',
    'link_uri': 'Web address', 'link_goto': 'Page in this document', 'link_gotor': 'Page in another PDF',
    'link_launch': 'Open file', 'link_named': 'Named action',
    'named_FirstPage': 'First page', 'named_LastPage': 'Last page', 'named_NextPage': 'Next page',
    'named_PrevPage': 'Previous page',
    'attachments_title': 'Embedded files', 'attachments_hint': 'Files carried inside the PDF.',
    'attachments_add': 'Add Files…', 'attachments_save': 'Save…', 'attachments_remove': 'Remove',
    'attachments_none': 'No embedded files.',
    'layers_title': 'Layers (optional content)', 'layers_hint': 'Turn layers on or off.',
    'layers_none': 'This document has no layers.', 'layers_new': 'New layer', 'layers_new_name': 'Name',
    'layers_apply_view': 'Apply to View',

    # Compare, search, style, snapshot
    'compare_with': 'Compare with', 'compare_hint': 'Compares the open document with another PDF.',
    'compare_file': 'Other PDF', 'compare_method': 'Method', 'compare_text': 'Text (word by word)',
    'compare_visual': 'Appearance (pixel by pixel)', 'compare_mark': 'Open the other PDF with changes highlighted',
    'compare_mark_hint': 'Text comparison only.', 'compare_results': 'Differences', 'compare_summary': 'Summary',
    'compare_not_run': 'Not compared yet.', 'compare_run': 'Compare', 'compare_running': 'Comparing…',
    'compare_identical': 'No differences were found.',
    'compare_text_summary': '{} change(s); {:.1f}% similar.', 'compare_visual_summary': '{} page(s) differ.',
    'compare_insert': 'Added', 'compare_delete': 'Removed', 'compare_replace': 'Changed',
    'compare_marked_opened': 'Opened the other document with changes highlighted.',
    'search_query': 'Search', 'search_regex': 'Regular expression', 'search_regex_hint': 'Python syntax, e.g. '
                                                                                         r'\d{4}-\d{2}',
    'search_case': 'Match case', 'search_whole_word': 'Whole words only', 'search_results': 'Results',
    'search_find_all': 'Find All', 'search_found': '{} match(es).', 'search_enter_query': 'Enter text to find.',
    'search_option_case': 'Match case', 'search_option_word': 'Whole words only',
    'search_option_regex': 'Regular expression',
    'text_style_details': 'Text under the selection', 'text_style_text': 'Text', 'text_style_font': 'Font',
    'text_style_size': 'Size', 'text_style_color': 'Color', 'text_style_bold': 'Bold',
    'text_style_italic': 'Italic', 'text_style_opacity': 'Opacity', 'text_style_render': 'Rendering',
    'text_style_same': 'Same font and size ({})',
    'text_style_need_selection': 'Select some text on the page first.',
    'render_mode_0': 'Fill', 'render_mode_1': 'Outline', 'render_mode_2': 'Fill and outline',
    'render_mode_3': 'Invisible',
    'snapshot_need_selection': 'Select an area on the page first.',

    # Status messages
    'status_new_tab_created': 'Created in a new tab. Save it to keep it.',
    'status_pages_inserted': 'Inserted {} page(s).', 'status_pages_extracted': 'Extracted {} page(s).',
    'status_pages_deleted': 'Deleted {} page(s).', 'status_split_done': 'Saved {} file(s) to {}.',
    'status_pages_reversed': 'Page order reversed.', 'status_pages_collated': 'Pages collated.',
    'status_blank_removed': 'Removed {} blank page(s): {}.', 'status_rotation_removed': 'Updated {} page(s).',
    'status_overlay_applied': 'Applied to {} page(s).', 'status_headers_applied': 'Added to {} page(s).',
    'status_labels_saved': 'Page labels updated.', 'status_boxes_saved': 'Page boxes updated on {} page(s).',
    'status_markup_added': 'Annotation added.', 'status_annotations_exported': 'Annotations exported.',
    'status_annotations_imported': 'Imported {} annotation(s); {} skipped.',
    'status_annotations_flattened': 'Flattened {} annotation(s).',
    'status_security_saved': 'Protected copy saved.', 'status_security_removed': 'Unprotected copy saved.',
    'status_sanitized': 'Sanitized copy saved.', 'status_converted': 'Converted {}.',
    'status_images_combined': 'Combined {} image(s).', 'status_optimized': 'Optimized copy saved.',
    'status_ocr_done': 'Recognized text on {} page(s).', 'status_images_exported': 'Exported {} page(s).',
    'status_viewer_settings_saved': 'Viewer settings updated.',
    'status_bookmarks_generated': 'Created {} bookmark(s).', 'status_link_added': 'Link added.',
    'status_links_detected': 'Linked {} web address(es).', 'status_layers_saved': 'Layers updated.',
    'status_snapshot_copied': 'Copied a {}×{} image to the clipboard.',

    # Forms structure and scripts
    'menu_form_structure': 'Form Structure and Scripts…',
    'forms_js_notice': 'pdfLX does not run JavaScript. Scripts listed here run in other PDF readers.',
    'forms_hierarchy': 'Field hierarchy',
    'forms_hierarchy_hint': 'Group top-level fields under a parent so they share a name prefix (parent.child).',
    'forms_parent_name': 'New parent name', 'forms_group_selected': 'Group Selected Fields',
    'forms_ungroup': 'Ungroup', 'forms_group': 'group', 'forms_none': 'This document has no form fields.',
    'forms_scripts': 'JavaScript', 'forms_no_scripts': 'No JavaScript was found.',
    'forms_remove_script': 'Remove', 'forms_add_script': 'Add or replace a field script',
    'forms_add_script_hint': 'An empty script removes the event handler.', 'forms_field': 'Field',
    'forms_event': 'Event', 'forms_save_script': 'Save Script', 'forms_choose_field': 'Choose a field.',
    'status_forms_updated': 'Form updated.',
    'form_multi_select_hint': 'Select every value that applies.',
    # Comments sidebar
    'comments_filter_placeholder': 'Filter by text or author', 'comments_filter_all_types': 'All types',
    'comments_filter_all_states': 'Any status', 'comments_filter_current_page': 'Current page only',
    'comments_no_match': 'No comments match the filters.', 'comments_reply': 'Reply',
    'comments_reply_placeholder': 'Write a reply', 'comments_set_state': 'Set review status',
    'comments_properties': 'Annotation Properties',
    'comments_state_none': 'No status', 'comments_state_None': 'Clear status',
    'comments_state_Accepted': 'Accepted', 'comments_state_Rejected': 'Rejected',
    'comments_state_Cancelled': 'Cancelled', 'comments_state_Completed': 'Completed',
    'annot_subject': 'Subject', 'annot_flags': 'Behaviour',
    'annot_flags_hint': 'Readers interpret these flags; some ignore a few of them.',
    'annot_flag_hidden': 'Hidden', 'annot_flag_print': 'Print with the page',
    'annot_flag_no_zoom': 'Keep size when zooming', 'annot_flag_no_rotate': 'Keep upright when rotating',
    'annot_flag_no_view': 'Do not show on screen', 'annot_flag_read_only': 'Read-only',
    'annot_flag_locked': 'Locked (cannot be moved or deleted)', 'annot_flag_locked_contents': 'Contents locked',
    # Redaction options
    'redact_replacement': 'Replacement text', 'redact_fill': 'Fill color', 'redact_no_fill': 'No fill (transparent)',
    'redact_images': 'Images under the area',
    'redact_images_pixels': 'Blank only the covered pixels',
    'redact_images_remove': 'Remove each overlapping image entirely',
    'redact_images_keep': 'Keep images (not secure)',

    # Graphics
    'menu_export_diagram': 'Diagram or Selection…', 'menu_export_vector_svg': 'Vector Drawings as SVG',
    'menu_images_manager': 'Images…',
    'diagram_none': 'This page has no vector diagrams. Select an area to export it.',
    'diagram_area': 'Area', 'diagram_hint': 'Vector drawings are grouped into diagrams automatically.',
    'diagram_selection': 'Selected area', 'diagram_cluster': 'Diagram {} ({}×{} pt)',
    'diagram_snap': 'Expand to whole diagrams', 'diagram_snap_hint': 'Includes every diagram touching the selection.',
    'diagram_vectors_only': 'Vector paths only', 'diagram_vectors_only_hint': 'Leave out text and images.',
    'images_manager_title': 'Images in this document',
    'images_manager_hint': 'Replacing an image updates every place it appears.',
    'images_save_all': 'Save All Images (ZIP)…', 'images_none': 'This document contains no images.',
    'images_transparent': 'transparent', 'images_placements': '{} placement(s) on pages {}',
    'images_replace_everywhere': 'Replace Everywhere…',
    'status_image_replaced': 'Image replaced on {} page(s).', 'status_images_saved': 'Saved {} image(s).',

    # Authoring
    'menu_compose': 'Compose Document…', 'menu_rich_text': 'Formatted Text Box…', 'menu_watermark': 'Watermark…',
    'menu_mail_merge': 'Mail Merge from CSV…',
    'compose_content': 'Content', 'compose_hint': 'Text flows across as many pages as needed. '
                                                   'A line with \\pagebreak starts a new page.',
    'compose_layout': 'Layout', 'compose_toc': 'Table of contents',
    'compose_toc_hint': 'Linked entries for headings with stable page numbers; headings also become bookmarks.',
    'compose_toc_title': 'Contents', 'compose_page_numbers': 'Page numbers', 'compose_css': 'Extra CSS (optional)',
    'status_composed': 'Created a {}-page document.',
    'rich_text_hint': 'Enter the position below, or select an area on the page first.',
    'rich_text_hint_selection': 'The text is fitted into the selected area.',
    'status_rich_text_added': 'Formatted text added.',
    'watermark_text': 'Text', 'watermark_hint': 'Any angle; tiling repeats the text across the page.',
    'watermark_angle': 'Angle (°, counter-clockwise)', 'watermark_tile': 'Repeat across the page',
    'watermark_behind': 'Behind the page content', 'watermark_behind_hint': 'May be hidden by opaque backgrounds.',
    'merge_template': 'Template (this document)',
    'merge_hint': 'CSV columns fill form fields with the same name and replace {{column}} text placeholders.',
    'merge_fields': 'Form fields', 'merge_placeholders': 'Text placeholders', 'merge_data': 'Data',
    'merge_csv': 'CSV file', 'merge_matched': 'Records', 'merge_matched_value': '{} record(s); matched: {}',
    'merge_no_match': 'No CSV column matches a field or placeholder in this document.',
    'merge_combined': 'One combined document (new tab)', 'merge_separate': 'One file per record',
    'merge_filename': 'File name pattern ({n} or {column})', 'merge_flatten': 'Flatten form fields',
    'merge_flatten_hint': 'Makes filled values part of the page.', 'status_merged': 'Merged {} record(s).',

    # Signature internals and repaired files
    'pkcs7_subfilter': 'Signature format', 'pkcs7_digest': 'Digest algorithm',
    'pkcs7_algorithm': 'Signature algorithm', 'pkcs7_byte_range': 'Signed byte range',
    'pkcs7_timestamp': 'Trusted timestamp', 'pkcs7_reason': 'Reason', 'pkcs7_location': 'Location',
    'pkcs7_certificate': 'Certificate {}', 'pkcs7_save_container': 'Save PKCS#7 (.p7s)…',
    'pkcs7_save_chain': 'Save Certificates (PEM)…',
    'repaired_notice': 'This file was damaged and has been repaired in memory.',
    'repaired_save_copy': 'Save Repaired Copy',

    # Recovery
    'recovery_title': 'Recover unsaved documents?',
    'recovery_body': 'pdfLX closed unexpectedly. These documents had unsaved changes:\n{}',
    'recovery_recover': 'Recover', 'recovery_discard': 'Discard', 'recovery_later': 'Ask Next Time',

    # Batch
    'menu_batch': 'Batch Process Files…', 'batch_run': 'Run…', 'batch_files': 'Files',
    'batch_files_hint': 'Originals are never changed; results are written to a folder you choose.',
    'batch_choose': 'Input files', 'batch_operation': 'Operation', 'batch_text': 'Text',
    'batch_optimize': 'Reduce file size', 'batch_sanitize': 'Sanitize', 'batch_protect': 'Add password protection',
    'batch_watermark': 'Add watermark', 'batch_bates': 'Bates numbering (continuous across files)',
    'batch_rasterize': 'Flatten to images', 'batch_gray': 'Convert to grayscale',
    'batch_to_pdf': 'Convert to PDF', 'batch_markdown': 'Export Markdown text',
    'batch_failed': '{} file(s) failed.', 'security_owner_required': 'Enter an owner password.',

    # Viewer
    'menu_page_layout': 'Page layout', 'layout_page': 'Single page', 'layout_continuous': 'Continuous',
    'layout_spread': 'Two pages', 'layout_book': 'Book (cover on its own)',
    'menu_presentation': 'Presentation', 'presentation_hint': 'Arrow keys change slides. Press Esc to leave.',
    'menu_side_viewer': 'Side-by-Side Viewer', 'side_viewer_title': 'Side-by-side',
    'side_viewer_refresh': 'Refresh', 'menu_measure': 'Measure', 'menu_measure_settings': 'Measurement Scale…',
    'measure_hint': 'Drag to measure a distance; hold Ctrl for an area. Scale: {}.',
    'measure_area': 'area', 'measure_perimeter': 'perimeter', 'measure_keep': 'Keep as Annotation',
    'measure_units': 'Units and scale', 'measure_units_hint': 'Use a scale for drawings, e.g. 100 for 1:100.',
    'measure_unit': 'Unit', 'measure_scale': 'Scale factor',
    'measure_scale_hint': 'Real-world units per unit on paper.', 'status_measure_saved': 'Measurement scale saved.',

    # Advanced structure
    'menu_einvoice': 'Attach E-Invoice (Factur-X / ZUGFeRD)…', 'menu_portfolio': 'Create Portfolio…',
    'menu_object_inspector': 'PDF Object Inspector…',
    'einvoice_title': 'Invoice XML', 'einvoice_hint': 'Embeds the UN/CEFACT Cross Industry Invoice as an '
                                                      'associated file and adds Factur-X metadata.',
    'einvoice_xml': 'Invoice XML file', 'einvoice_profile': 'Profile', 'einvoice_filename': 'Attachment name',
    'einvoice_warning': 'Factur-X and ZUGFeRD also require the PDF itself to be PDF/A-3 conformant. pdfLX does '
                        'not convert or validate PDF/A; check the result with a Factur-X validator before sending.',
    'einvoice_existing': 'Existing invoice', 'einvoice_existing_hint': 'Already embedded in this document.',
    'status_einvoice_attached': 'Invoice XML attached.',
    'portfolio_title': 'Files', 'portfolio_hint': 'Creates a PDF that carries the files, with a cover page.',
    'portfolio_files': 'Files to include', 'portfolio_default_title': 'Portfolio',
    'status_portfolio_created': 'Portfolio with {} file(s) created.',
    'objects_warning': 'Advanced: editing raw objects can make the document unreadable. Changes can be undone.',
    'objects_read_only': 'Switch to Edit mode to change objects.',
    'objects_find': 'Find objects', 'objects_query': 'Object number, /Type, or text',
    'objects_selected': 'Object', 'objects_object': 'Object {} 0 R', 'objects_save': 'Save Object',
    'objects_binary_stream': 'This object has a binary stream; only its dictionary can be edited here.',
    'status_object_saved': 'Object {} saved.',

    # Drawing
    'menu_draw_shape': 'Draw Shape…', 'menu_node_editor': 'Edit Drawing Nodes…',
    'shape_kind': 'Shape', 'shape_star': 'Star', 'shape_polygon': 'Regular polygon', 'shape_triangle': 'Triangle',
    'shape_arrow': 'Block arrow', 'shape_sector': 'Sector (pie slice)', 'shape_arc': 'Arc',
    'shape_rounded_rectangle': 'Rounded rectangle', 'shape_points': 'Points / sides',
    'shape_inner': 'Inner size or corner radius (%)', 'shape_start_angle': 'Start angle (°)',
    'shape_sweep': 'Sweep (°)', 'status_shape_added': 'Shape added.',
    'nodes_need_stroke': 'Select a pen drawing first (Edit mode, Select tool).',
    'nodes_rotated': 'Reset the drawing\'s rotation before editing its nodes.',
    'nodes_title': 'Path nodes', 'nodes_hint': 'On the page: drag a node to move it, Ctrl+click the path to '
                                               'insert a node, Shift+click a node to delete it. Esc finishes.',
    'nodes_count': 'Nodes', 'nodes_simplify_tolerance': 'Simplify tolerance (pt)',
    'nodes_smooth_iterations': 'Smoothing passes', 'nodes_simplify': 'Simplify', 'nodes_smooth': 'Smooth',
    'nodes_edit_on_page': 'Edit on Page', 'nodes_status': 'Editing nodes. Press Esc or choose another tool to finish.',

    'menu_enter_edit_mode': 'Switch to Edit Mode to Enable All Tools',

    # Form scripts, behaviour, buttons, and data
    'menu_form_scripts': 'Run Form Scripts (Calculations and Validation)',
    'menu_form_import': 'Import Form Data…', 'menu_form_export': 'Export Form Data…', 'btn_import': 'Import',
    'form_scripts_disabled': 'Form scripts are turned off (main menu > Run Form Scripts).',
    'form_script_ran': 'Button script ran.', 'form_pick_date': 'Pick a date',
    'form_value_rejected': 'Value not accepted',
    'button_kind': 'Button', 'button_action': 'Button action', 'button_action_reset': 'Reset form',
    'button_action_goto': 'Go to page', 'button_action_submit': 'Submit form', 'button_action_url': 'Open web address',
    'button_action_print': 'Print document', 'button_action_javascript': 'Run JavaScript',
    'button_destination_page': 'Destination page', 'button_url': 'Address (https:// or mailto:)',
    'button_submit_format': 'Submission format', 'button_script': 'Script',
    'button_no_action': 'No supported button action. Use Properties to choose one.',
    'button_submit_title': 'Submit form',
    'button_submit_body': 'This button submits the form to {} when the PDF is filled in a reader that '
                          'supports submission. pdfLX does not send data over the network; you can export '
                          'the form data instead.',
    'button_submit_export': 'Export Form Data…',
    'submit_send': 'Submit',
    'submit_bad_address': 'This button has no address pdfLX can submit to ({}).',
    'submit_missing': 'Fill in the required fields before submitting: {}',
    'submit_confirm': 'Send the form data ({}) to {}?',
    'submit_confirm_mail': 'Open your email app with the form data addressed to {}?',
    'submit_unencrypted': 'The connection is not encrypted (http), so others on the network could read the data.',
    'submit_sending': 'Submitting form to {}…',
    'submit_done_title': 'Form submitted',
    'submit_done': '{} accepted the form (HTTP {}).',
    'submit_done_status': 'Form submitted (HTTP {}).',
    'submit_failed_title': 'Form not submitted',
    'submit_failed': 'The form could not be submitted to {}: {}',
    'submit_failed_status': 'Form submission failed.',
    'submit_retry': 'Try Again',
    'submit_mail_subject': 'Form submission',
    'qf_title': 'Add fields',
    'tool_create_field_tip': 'Create one field with every option set in a dialog first.',
    'tool_fill_forms_tip': 'Add fields to build a form, or list, fill and edit this document’s fields.',
    'tool_flatten_tip': 'Turn form fields into ordinary page content.',
    'qf_open_hint': 'Type a label, pick a field type, then drag or click on the page.',
    'menu_group_create': 'Create',
    'menu_alignment_guides': 'Alignment Guides',
    'redact_section_patterns': 'Sensitive data',
    'replace_title': 'Find and Replace',
    'organize_title': 'Organize Pages',
    'organize_count': '{} pages · {} selected',
    'organize_done': 'Done',
    'organize_rotate_left': 'Rotate left',
    'organize_rotate_right': 'Rotate right',
    'organize_duplicate': 'Duplicate',
    'organize_insert': 'Insert blank page after the selection',
    'organize_extract': 'Extract to a new document',
    'organize_delete': 'Delete',
    'organize_moved': 'Moved {} page(s).',
    'organize_rotated': 'Rotated {} page(s).',
    'organize_deleted': 'Deleted {} page(s).',
    'organize_duplicated': 'Duplicated {} page(s).',
    'organize_inserted': 'Inserted a blank page.',
    'organize_need_edit': 'Switch to Edit mode to reorder, rotate, duplicate, insert or delete pages. Extracting works in any mode.',
    'organize_protected': 'This document is protected against changes; pages can only be viewed.',
    'replace_button': 'Replace…',
    'replace_find': 'Find',
    'replace_with': 'Replace with',
    'replace_scope': 'Pages',
    'replace_scope_all': 'All pages',
    'replace_scope_page': 'Current page',
    'replace_select_all': 'Select all',
    'replace_apply': 'Replace',
    'replace_type': 'Type the text to find.',
    'replace_none': 'No matches in editable text.',
    'replace_found': '{} matches on {} pages. Untick any you want to keep.',
    'replace_row_meta': 'Page {} · {} match(es)',
    'replace_nothing': 'Tick at least one change to replace.',
    'replace_done': 'Replaced {} matches. Undo reverts them all at once.',
    'replace_bad_pattern': 'Invalid replacement: {}',
    'replace_note': 'Each line of text is replaced as a whole; a phrase split across two lines is not matched. With regular expressions, \\1 inserts a captured group.',
    'redact_pattern_email': 'Email addresses',
    'redact_pattern_url': 'Web addresses',
    'redact_pattern_iban': 'IBANs (checked)',
    'redact_pattern_card': 'Card numbers (checked)',
    'redact_pattern_date': 'Dates',
    'redact_pattern_phone': 'Phone numbers',
    'redact_pattern_number_id': 'ID numbers (letters and digits)',
    'redact_review_more': '…and {} more',
    'redact_nothing_found': 'Nothing to redact: select an area, enter text, or choose sensitive data to find.',
    'menu_group_edit': 'Edit & Insert',
    'menu_group_forms': 'Forms',
    'menu_preferences': 'Preferences',
    'menu_more_tools': 'More tools',
    'menu_section_review': 'Review',
    'menu_section_page_look': 'Page appearance',
    'menu_section_protect': 'Protect',
    'qf_required_tip': 'Required field',
    'qf_group_inputs': 'Inputs',
    'qf_group_choices': 'Choices',
    'qf_group_buttons': 'Buttons & signing',
    'qf_text_tip': 'Single-line text',
    'qf_multiline_tip': 'Multi-line text area',
    'qf_date_tip': 'Date with a date picker',
    'qf_email_tip': 'Email address, checked when entered',
    'qf_phone_tip': 'Phone number (digits, spaces, + ( ) -)',
    'qf_number_tip': 'Number with two decimals',
    'qf_dropdown_tip': 'Pick one choice from a list',
    'qf_list_tip': 'List box of choices',
    'qf_checkbox_tip': 'Checkbox',
    'qf_radio_tip': 'Radio group, one button per choice',
    'qf_signature_tip': 'Certificate signature field',
    'qf_submit_tip': 'Button that submits the form to an address',
    'qf_reset_tip': 'Button that clears the form',
    'qf_section_style': 'Style',
    'qf_style_sub': 'Colors, font and borders of new fields',
    'qf_snap_sub': 'Line fields up with each other',
    'qf_section_tools': 'Tools',
    'qf_copies_sub': 'Repeat the selected fields in rows and columns',
    'qf_apply_style_sub': 'Give the selected fields the form style',
    'qf_detect_sub': 'Turn boxes and lines on this page into fields',
    'qf_tab_order_sub': 'Order fields by rows or columns',
    'qf_validate': 'Check required fields',
    'qf_validate_sub': 'Find required fields that are still empty',
    'qf_scripts': 'Field scripts',
    'qf_scripts_sub': 'JavaScript for the selected field',
    'qf_full_field': 'Field with all options',
    'qf_full_field_sub': 'Set every option in a dialog first',
    'qf_section_fields': 'Fields',
    'qf_fields_hint': 'Click a field on the page to fill it; Select moves or resizes it.',
    'qf_fields_empty': 'No fields yet. Type a label above, pick a field type, then drag on the page.',
    'js_title': 'Scripts · {}',
    'js_event': 'Event',
    'js_examples': 'Insert example',
    'js_clear': 'Clear',
    'js_note': 'Standard Acrobat form JavaScript, saved in the PDF. pdfLX runs Keystroke, Format, Validate and Calculate scripts while you fill; other PDF readers run all events.',
    'js_saved': 'Scripts saved for {}.',
    'js_snippet_uppercase': 'Type in capitals',
    'js_snippet_digits': 'Allow digits only',
    'js_snippet_min_length': 'Require at least 3 characters',
    'js_snippet_range': 'Number between 1 and 100',
    'js_snippet_sum': 'Price × quantity',
    'js_snippet_today': 'Fill in today’s date',
    'js_snippet_show_hide': 'Show another field when filled',
    'js_snippet_copy': 'Copy into another field',
    'js_snippet_message': 'Show a message on click',
    'qf_label_hint': 'Label for the next field',
    'qf_text': 'Text',
    'qf_multiline': 'Paragraph',
    'qf_date': 'Date',
    'qf_email': 'Email',
    'qf_phone': 'Phone',
    'qf_number': 'Number',
    'qf_dropdown': 'Dropdown',
    'qf_list': 'List',
    'qf_checkbox': 'Checkbox',
    'qf_radio': 'Radio',
    'qf_signature': 'Signature',
    'qf_submit': 'Submit',
    'qf_reset': 'Reset',
    'qf_choices_hint': 'Choices, separated by commas',
    'qf_url_hint': 'Submit address (https://…)',
    'qf_place_hint': 'Drag on the page to draw the field, or click to place it at the default size. Esc stops.',
    'qf_style': 'Form style…',
    'qf_label_above': 'Above',
    'qf_label_left': 'Left',
    'qf_label_none': 'None',
    'qf_label_position': 'Labels',
    'qf_snap': 'Alignment guides',
    'qf_copies': 'Multiple copies',
    'qf_apply_style': 'Apply style',
    'qf_detect': 'Detect fields',
    'qf_tab_order': 'Tab order',
    'qf_need_url': 'Enter the submit address first.',
    'qf_placed': 'Field “{}” placed. Type the next label or draw again.',
    'qf_style_title': 'Form Style',
    'qf_style_font': 'Field font',
    'qf_style_size': 'Font size (0 = automatic)',
    'qf_style_border': 'Border width · pt',
    'qf_style_text_color': 'Text color',
    'qf_style_border_color': 'Border color',
    'qf_style_fill_color': 'Background color',
    'qf_style_label_color': 'Label color',
    'qf_style_transparent': 'Transparent background',
    'qf_style_label_size': 'Label size',
    'qf_style_date': 'Date format',
    'qf_tab_rows': 'Order by rows',
    'qf_tab_columns': 'Order by columns',
    'qf_tab_show': 'Show tab order numbers',
    'qf_tab_done': 'Tab order updated for {} fields.',
    'qf_detect_none': 'No empty boxes or fill-in lines were found on this page.',
    'qf_detect_found': 'Found {} text areas and {} checkboxes on this page. Create form fields for them?',
    'qf_detect_create': 'Create Fields',
    'qf_detect_done': 'Created {} form fields.',
    'qf_copies_select': 'Select one or more fields first.',
    'qf_copies_title': 'Create Multiple Copies',
    'qf_copies_rows': 'Rows',
    'qf_copies_columns': 'Columns',
    'qf_copies_gap_x': 'Horizontal gap · pt',
    'qf_copies_gap_y': 'Vertical gap · pt',
    'qf_restyled': 'Styled {} fields.',
    'qf_copies_too_many': 'The copies do not fit on the page; use fewer rows or columns.',
    'qf_copies_done': 'Created {} copies.',
    'form_match_style': 'Give the others the first selected field’s style',
    'behaviour_tab': 'Format & Calculation', 'behaviour_format': 'Format',
    'behaviour_format_none': 'None', 'behaviour_format_number': 'Number', 'behaviour_format_percent': 'Percentage',
    'behaviour_format_date': 'Date', 'behaviour_format_time': 'Time', 'behaviour_format_special': 'Special',
    'behaviour_decimals': 'Decimal places', 'behaviour_separator': 'Separator style',
    'behaviour_negative': 'Negative numbers', 'behaviour_currency': 'Currency symbol',
    'behaviour_currency_before': 'Symbol before the number', 'behaviour_date_format': 'Date format',
    'behaviour_time_format': 'Time format', 'behaviour_special': 'Special format',
    'behaviour_special_0': 'ZIP code', 'behaviour_special_1': 'ZIP+4', 'behaviour_special_2': 'Phone number',
    'behaviour_special_3': 'Social Security number',
    'behaviour_minimum': 'Value must be at least', 'behaviour_minimum_value': 'Minimum',
    'behaviour_maximum': 'Value must be at most', 'behaviour_maximum_value': 'Maximum',
    'behaviour_calculate': 'Calculate', 'behaviour_calc_none': 'Not calculated', 'behaviour_calc_SUM': 'Sum of',
    'behaviour_calc_AVG': 'Average of', 'behaviour_calc_PRD': 'Product of', 'behaviour_calc_MIN': 'Minimum of',
    'behaviour_calc_MAX': 'Maximum of', 'behaviour_calc_custom': 'Custom script',
    'behaviour_sources': 'Fields', 'behaviour_no_sources': 'Create other fields first.',
    'behaviour_custom': 'Calculation script',
    'behaviour_note': 'Saved as standard Acrobat form scripts, so formatting, validation, and calculations '
                      'also work in other PDF readers.',
    'forms_calc_order': 'Calculation order',
    'forms_calc_order_hint': 'Fields are recalculated in this order; put a field before the fields that use it.',
    'forms_calc_none': 'No calculated fields.',
    'formdata_export_title': 'Field values', 'formdata_export_hint': 'XFDF and FDF are the standard PDF formats; '
                                                                        'JSON and CSV suit spreadsheets and scripts.',
    'formdata_fields': 'Fields', 'formdata_import_title': 'Field values',
    'formdata_import_hint': 'Values are matched to fields by their full names (parent.child).',
    'formdata_file': 'Data file', 'formdata_files': 'Form data (FDF, XFDF, JSON, CSV)', 'formdata_match': 'Match',
    'formdata_match_value': '{}: {} of {} value(s) match this form.', 'formdata_unmatched': 'Not found: {}.',
    'formdata_csv_row': 'CSV row', 'status_formdata_exported': 'Exported {} field value(s).',
    'status_formdata_imported': 'Filled {} field(s); {} name(s) did not match.',

    # Existing keys that previously fell back to the key name
    'delete_page_title': 'Delete Page', 'err_image_delete_title': 'Could Not Delete Image',
    'err_image_delete_msg': 'The image could not be deleted.', 'image_delete_confirm_title': 'Delete Image?',
    'image_delete_confirm_msg': 'Delete the selected image?',
    'dbg_creating_drag_command': 'Creating drag command', 'dbg_format_change_saved': 'Format change saved',
    'dbg_tool_changed': 'Tool changed: {}',
    # Shared dialog and inspector layout.
    'props_position': 'Position',
    'props_x': 'Horizontal',
    'props_y': 'Vertical',
    'props_size': 'Size & rotation',
    'props_rotation': 'Rotation',
    'stamp_place': 'Place on Page',
    'stamp_templates': 'Templates',
    'stamp_save_template': 'Save as Template',
    'stamp_save_template_body': 'Saved templates appear in the gallery every time you add a stamp.',
    'stamp_template_name': 'Template name',
    'stamp_remove_template': 'Remove this saved template',
    'stamp_fields_hint': 'Use + to insert the date, time or author; they are filled in when the stamp is placed.',
    'stamp_details': 'Details line (optional)',
    'stamp_insert_field': 'Insert field',
    'stamp_field_date': 'Date',
    'stamp_field_time': 'Time',
    'stamp_field_datetime': 'Date and time',
    'stamp_field_author': 'Author name',
    'stamp_text_size': 'Text size',
    'stamp_text_size_hint': 'Largest size; long text shrinks to fit',
    'stamp_color_red': 'Red', 'stamp_color_green': 'Green', 'stamp_color_blue': 'Blue',
    'stamp_color_orange': 'Orange', 'stamp_color_purple': 'Purple', 'stamp_color_gray': 'Gray',
    'stamp_color_black': 'Black', 'stamp_color_custom': 'Custom color',
    'stamp_border_none': 'None', 'stamp_border_solid': 'Solid', 'stamp_border_double': 'Double',
    'stamp_border_dashed': 'Dashed',
    'stamp_fill': 'Tinted background',
    'stamp_fill_hint': 'A light wash of the stamp color behind the text',
    'stamp_width': 'Width',
    'stamp_tilt': 'Tilt',
    'stamp_author_name': 'Name shown as the stamp author',
    'stamp_dimensions': '{} × {} pt',
    'stamp_place_hint': 'After clicking Place on Page, click anywhere on the page to drop the stamp. Press Escape to stop.',
    'stamp_edit_hint': 'Changes replace the selected stamp in the same position.',
    'stamp_tpl_approved': 'Approved', 'stamp_tpl_not_approved': 'Not approved', 'stamp_tpl_draft': 'Draft',
    'stamp_tpl_confidential': 'Confidential', 'stamp_tpl_final': 'Final', 'stamp_tpl_for_comment': 'For comment',
    'stamp_tpl_reviewed': 'Reviewed', 'stamp_tpl_received': 'Received', 'stamp_tpl_paid': 'Paid',
    'stamp_tpl_completed': 'Completed', 'stamp_tpl_urgent': 'Urgent', 'stamp_tpl_void': 'Void',
    'stamp_tpl_copy': 'Copy', 'stamp_tpl_sign_here': 'Sign here',
    'props_width': 'Width',
    'redact_section_search': 'Search',
    'props_height': 'Height',
    'props_font_size': 'Font size',
    'props_stroke_width': 'Stroke width',
    'props_text': 'Text',
    'props_style': 'Style',
    'props_appearance': 'Appearance',
    'props_stroke_color': 'Stroke color',
    'image_tools_title': 'Image',
    'image_tools_close': 'Close image tools',
    'image_rotate_left': 'Rotate left 90°',
    'image_rotate_right': 'Rotate right 90°',
    'image_flip_horizontal': 'Flip horizontally',
    'image_flip_vertical': 'Flip vertically',
    'image_restore_ratio': 'Restore original proportions',
    'image_reset': 'Reset crop and appearance',
    'image_replace': 'Replace image',
    'image_replace_short': 'Replace',
    'image_section_appearance': 'Appearance',
    'image_section_border': 'Border',
    'image_section_effects': 'Effects',
    'image_opacity': 'Opacity',
    'image_tilt': 'Tilt',
    'image_corners': 'Corner radius',
    'image_border_width': 'Width',
    'image_border_color': 'Color',
    'image_crop': 'Crop',
    'image_crop_active': 'Edges trimmed',
    'image_crop_left': 'Left',
    'image_crop_top': 'Top',
    'image_crop_right': 'Right',
    'image_crop_bottom': 'Bottom',
    'image_shadow': 'Drop shadow',
    'image_shadow_distance': 'Distance',
    'image_shadow_strength': 'Strength',
    'print_title': 'Print',
    'print_action': 'Print',
    'print_save_pdf': 'Save PDF',
    'print_group_printer': 'Printer',
    'print_printer': 'Printer',
    'print_searching': 'Looking for printers…',
    'print_default': 'Default printer',
    'print_output_file': 'Output file',
    'print_copies': 'Copies',
    'print_collate': 'Collate',
    'print_collate_hint': 'Print complete copies one after another',
    'print_group_pages': 'Pages',
    'print_reverse': 'Reverse order',
    'print_group_layout': 'Layout',
    'print_paper': 'Paper size',
    'print_orientation': 'Orientation',
    'print_orientation_auto': 'Automatic',
    'print_orientation_portrait': 'Portrait',
    'print_orientation_landscape': 'Landscape',
    'print_scaling': 'Scaling',
    'print_scale_fit': 'Fit to printable area',
    'print_scale_shrink': 'Shrink oversized pages',
    'print_scale_actual': 'Actual size',
    'print_group_output': 'Output',
    'print_color': 'Color',
    'print_color_color': 'Color',
    'print_color_gray': 'Grayscale',
    'print_duplex': 'Two-sided',
    'print_duplex_off': 'Off',
    'print_duplex_long': 'Flip on long edge',
    'print_duplex_short': 'Flip on short edge',
    'print_system_dialog': 'System print dialog',
    'print_system_dialog_hint': 'Printer-specific options such as trays and quality',
    'print_prev_page': 'Previous page',
    'print_next_page': 'Next page',
    'print_page_of': 'Page {} of {}',
    'print_summary': '{} pages · {} sheets of paper',
    'print_no_pages': 'Enter a valid page range',
    'pdf_password_open': 'Unlock',
    'metadata_group': 'Document information',
    'bookmark_new': 'New bookmark',
    'form_fields_selected': '{} fields',
    'form_align_left': 'Align left edges to the first selected field',
    'form_align_hcenter': 'Center horizontally on the first selected field',
    'form_align_right': 'Align right edges to the first selected field',
    'form_align_top': 'Align top edges to the first selected field',
    'form_align_vcenter': 'Center vertically on the first selected field',
    'form_align_bottom': 'Align bottom edges to the first selected field',
    'form_distribute_h': 'Space evenly horizontally',
    'form_distribute_v': 'Space evenly vertically',
    'form_same_width': 'Match the width of the first selected field',
    'form_same_height': 'Match the height of the first selected field',
    'form_same_size': 'Match the size of the first selected field',
    'ai_title': 'AI Assistant',
    'ai_new_chat': 'New conversation',
    'ai_settings': 'AI Settings',
    'ai_attach': 'Attach images or PDFs',
    'ai_attach_filter': 'Images and PDFs',
    'ai_placeholder': 'Ask AI to edit this document, or attach a picture to recreate…',
    'ai_send': 'Send (Enter)',
    'ai_stop': 'Stop',
    'ai_working': 'Working…',
    'ai_stopping': 'Stopping after the current step…',
    'ai_no_model': 'No model selected',
    'ai_usage': '{} tokens used in this conversation',
    'ai_remove_attachment': 'Remove',
    'ai_settings_service': 'OpenRouter',
    'ai_api_key': 'API key',
    'ai_api_key_env': 'API key (from OPENROUTER_API_KEY)',
    'ai_model': 'Model ID',
    'ai_browse_models': 'Browse models',
    'ai_model_hint': 'Any OpenRouter model ID, for example provider/model-name. Pick one that accepts images and tools to work with pictures.',
    'ai_settings_advanced': 'Advanced',
    'ai_base_url': 'API base URL',
    'ai_max_steps': 'Step limit',
    'ai_max_steps_hint': 'Most tool calls the assistant may make per request',
    'ai_search_models': 'Search models',
    'ai_loading_models': 'Loading models…',
    'ai_models_hint': 'Models that accept images and tools. Prices are input / output.',
    'ai_model_required': 'Enter the model ID to use.',
    'ai_tool_info': 'Checked the document',
    'ai_tool_list': 'Read page {}',
    'ai_tool_render': 'Looked at page {}',
    'ai_tool_attachment': 'Looked at attachment {}',
    'ai_tool_add': 'Added {} elements on page {}',
    'ai_tool_edit': 'Edited {} elements on page {}',
    'ai_tool_delete': 'Deleted {} elements on page {}',
    'ai_tool_add_one': 'Added 1 element on page {}',
    'element_bring_front': 'Bring to Front (Ctrl+])',
    'element_send_back': 'Send to Back (Ctrl+[)',
    'shape_options': 'Shape options',
    'shape_corner_radius': 'Corner radius',
    'shape_opacity': 'Opacity',
    'shape_sides': 'Sides',
    'shape_star_points': 'Star points',
    'shape_star_depth': 'Inner radius',
    'shape_line_style': 'Line style',
    'line_solid': 'Solid',
    'line_dashed': 'Dashed',
    'line_dotted': 'Dotted',
    'line_options': 'Line options',
    'line_arrow_start': 'Arrow at start',
    'line_arrow_end': 'Arrow at end',
    'shape_rounded': 'Rounded rectangle',
    'shape_triangle': 'Triangle',
    'shape_right_triangle': 'Right triangle',
    'shape_diamond': 'Diamond',
    'shape_pentagon': 'Pentagon',
    'shape_hexagon': 'Hexagon',
    'shape_star': 'Star',
    'shape_arrow': 'Block arrow',
    'shape_callout': 'Speech callout',
    'tool_line': 'Line (Shift snaps the angle)',
    'tool_arrow_line': 'Arrow (Shift snaps the angle)',
    'tool_shape': 'Shape',
    'tool_line_label': 'Line',
    'ai_collapse': 'Hide conversation',
    'ai_expand': 'Show conversation',
    'ai_dock': 'Dock to the side',
    'ai_undock': 'Float at the bottom',
    'ai_steps': '{} steps',
    'ai_steps_one': '1 step',
    'ai_issues': '{} issues',
    'ai_issues_one': '1 issue',
    'ai_tool_edit_one': 'Edited 1 element on page {}',
    'ai_tool_delete_one': 'Deleted 1 element on page {}',
    'ai_tool_add_page': 'Added page {}',
    'ai_tool_delete_pages': 'Deleted pages {}',
    'ai_tool_goto': 'Went to page {}',
    'ai_tool_new_document': 'Created a new document',
    'ai_tool_fonts': 'Checked installed fonts',
    'ai_tool_measure': 'Measured text',
}

# Menu group labels, translated so the restructured menu reads naturally.
MENU_TRANSLATIONS = {
    'tr': {'menu_group_document': 'Belge', 'menu_group_pages': 'Sayfalar', 'menu_group_annotate': 'Açıklama',
           'menu_group_insert': 'Ekle ve Formlar', 'menu_group_protect': 'Koruma', 'menu_group_tools': 'Araçlar',
           'menu_view': 'Görünüm', 'menu_main_tip': 'Ana menü'},
    'fr': {'menu_group_document': 'Document', 'menu_group_pages': 'Pages', 'menu_group_annotate': 'Annoter',
           'menu_group_insert': 'Insérer et formulaires', 'menu_group_protect': 'Protéger',
           'menu_group_tools': 'Outils', 'menu_view': 'Affichage', 'menu_main_tip': 'Menu principal'},
    'de': {'menu_group_document': 'Dokument', 'menu_group_pages': 'Seiten', 'menu_group_annotate': 'Kommentieren',
           'menu_group_insert': 'Einfügen und Formulare', 'menu_group_protect': 'Schützen',
           'menu_group_tools': 'Werkzeuge', 'menu_view': 'Ansicht', 'menu_main_tip': 'Hauptmenü'},
    'es': {'menu_group_document': 'Documento', 'menu_group_pages': 'Páginas', 'menu_group_annotate': 'Anotar',
           'menu_group_insert': 'Insertar y formularios', 'menu_group_protect': 'Proteger',
           'menu_group_tools': 'Herramientas', 'menu_view': 'Ver', 'menu_main_tip': 'Menú principal'},
    'it': {'menu_group_document': 'Documento', 'menu_group_pages': 'Pagine', 'menu_group_annotate': 'Annota',
           'menu_group_insert': 'Inserisci e moduli', 'menu_group_protect': 'Proteggi',
           'menu_group_tools': 'Strumenti', 'menu_view': 'Visualizza', 'menu_main_tip': 'Menu principale'},
    'ru': {'menu_group_document': 'Документ', 'menu_group_pages': 'Страницы', 'menu_group_annotate': 'Комментарии',
           'menu_group_insert': 'Вставка и формы', 'menu_group_protect': 'Защита',
           'menu_group_tools': 'Инструменты', 'menu_view': 'Вид', 'menu_main_tip': 'Главное меню'},
}

# Form field arrange bar.
for _language, _values in {
    'tr': ['{} alan', 'Sol kenarları ilk seçilen alana hizala', 'İlk seçilen alana göre yatay ortala', 'Sağ kenarları ilk seçilen alana hizala', 'Üst kenarları ilk seçilen alana hizala', 'İlk seçilen alana göre dikey ortala', 'Alt kenarları ilk seçilen alana hizala', 'Yatay olarak eşit aralıkla dağıt', 'Dikey olarak eşit aralıkla dağıt', 'İlk seçilen alanın genişliğini uygula', 'İlk seçilen alanın yüksekliğini uygula', 'İlk seçilen alanın boyutunu uygula'],
    'fr': ['{} champs', 'Aligner les bords gauches sur le premier champ sélectionné', 'Centrer horizontalement sur le premier champ sélectionné', 'Aligner les bords droits sur le premier champ sélectionné', 'Aligner les bords supérieurs sur le premier champ sélectionné', 'Centrer verticalement sur le premier champ sélectionné', 'Aligner les bords inférieurs sur le premier champ sélectionné', 'Répartir horizontalement', 'Répartir verticalement', 'Même largeur que le premier champ sélectionné', 'Même hauteur que le premier champ sélectionné', 'Même taille que le premier champ sélectionné'],
    'de': ['{} Felder', 'Linke Kanten am zuerst gewählten Feld ausrichten', 'Horizontal am zuerst gewählten Feld zentrieren', 'Rechte Kanten am zuerst gewählten Feld ausrichten', 'Obere Kanten am zuerst gewählten Feld ausrichten', 'Vertikal am zuerst gewählten Feld zentrieren', 'Untere Kanten am zuerst gewählten Feld ausrichten', 'Horizontal gleichmäßig verteilen', 'Vertikal gleichmäßig verteilen', 'Breite des zuerst gewählten Felds übernehmen', 'Höhe des zuerst gewählten Felds übernehmen', 'Größe des zuerst gewählten Felds übernehmen'],
    'es': ['{} campos', 'Alinear bordes izquierdos con el primer campo seleccionado', 'Centrar horizontalmente en el primer campo seleccionado', 'Alinear bordes derechos con el primer campo seleccionado', 'Alinear bordes superiores con el primer campo seleccionado', 'Centrar verticalmente en el primer campo seleccionado', 'Alinear bordes inferiores con el primer campo seleccionado', 'Distribuir horizontalmente', 'Distribuir verticalmente', 'Igualar el ancho del primer campo seleccionado', 'Igualar la altura del primer campo seleccionado', 'Igualar el tamaño del primer campo seleccionado'],
    'it': ['{} campi', 'Allinea i bordi sinistri al primo campo selezionato', 'Centra orizzontalmente sul primo campo selezionato', 'Allinea i bordi destri al primo campo selezionato', 'Allinea i bordi superiori al primo campo selezionato', 'Centra verticalmente sul primo campo selezionato', 'Allinea i bordi inferiori al primo campo selezionato', 'Distribuisci orizzontalmente', 'Distribuisci verticalmente', 'Stessa larghezza del primo campo selezionato', 'Stessa altezza del primo campo selezionato', 'Stesse dimensioni del primo campo selezionato'],
    'ru': ['Полей: {}', 'Выровнять левые края по первому выбранному полю', 'Центрировать по горизонтали по первому выбранному полю', 'Выровнять правые края по первому выбранному полю', 'Выровнять верхние края по первому выбранному полю', 'Центрировать по вертикали по первому выбранному полю', 'Выровнять нижние края по первому выбранному полю', 'Распределить по горизонтали', 'Распределить по вертикали', 'Ширина как у первого выбранного поля', 'Высота как у первого выбранного поля', 'Размер как у первого выбранного поля'],
}.items():
    MENU_TRANSLATIONS[_language].update(zip(['form_fields_selected', 'form_align_left', 'form_align_hcenter', 'form_align_right', 'form_align_top', 'form_align_vcenter', 'form_align_bottom', 'form_distribute_h', 'form_distribute_v', 'form_same_width', 'form_same_height', 'form_same_size'], _values))

# AI assistant.
for _language, _values in {
    'tr': {'ai_title': 'Yapay Zekâ Asistanı', 'ai_new_chat': 'Yeni konuşma', 'ai_settings': 'Yapay Zekâ Ayarları', 'ai_attach': 'Görsel veya PDF ekle', 'ai_placeholder': 'Bu belgeyi düzenlemesini isteyin ya da yeniden oluşturmak için bir görsel ekleyin…', 'ai_send': 'Gönder (Enter)', 'ai_stop': 'Durdur', 'ai_working': 'Çalışıyor…', 'ai_api_key': 'API anahtarı', 'ai_model': 'Model kimliği', 'ai_settings_advanced': 'Gelişmiş', 'ai_max_steps': 'Adım sınırı'},
    'fr': {'ai_title': 'Assistant IA', 'ai_new_chat': 'Nouvelle conversation', 'ai_settings': 'Paramètres IA', 'ai_attach': 'Joindre des images ou des PDF', 'ai_placeholder': 'Demandez à l’IA de modifier ce document, ou joignez une image à recréer…', 'ai_send': 'Envoyer (Entrée)', 'ai_stop': 'Arrêter', 'ai_working': 'En cours…', 'ai_api_key': 'Clé API', 'ai_model': 'Identifiant du modèle', 'ai_settings_advanced': 'Avancé', 'ai_max_steps': 'Limite d’étapes'},
    'de': {'ai_title': 'KI-Assistent', 'ai_new_chat': 'Neue Unterhaltung', 'ai_settings': 'KI-Einstellungen', 'ai_attach': 'Bilder oder PDFs anhängen', 'ai_placeholder': 'Bitten Sie die KI, dieses Dokument zu bearbeiten, oder hängen Sie ein Bild zum Nachbauen an…', 'ai_send': 'Senden (Eingabe)', 'ai_stop': 'Stoppen', 'ai_working': 'Arbeitet…', 'ai_api_key': 'API-Schlüssel', 'ai_model': 'Modell-ID', 'ai_settings_advanced': 'Erweitert', 'ai_max_steps': 'Schrittlimit'},
    'es': {'ai_title': 'Asistente de IA', 'ai_new_chat': 'Nueva conversación', 'ai_settings': 'Ajustes de IA', 'ai_attach': 'Adjuntar imágenes o PDF', 'ai_placeholder': 'Pide a la IA que edite este documento o adjunta una imagen para recrearla…', 'ai_send': 'Enviar (Intro)', 'ai_stop': 'Detener', 'ai_working': 'Trabajando…', 'ai_api_key': 'Clave de API', 'ai_model': 'ID del modelo', 'ai_settings_advanced': 'Avanzado', 'ai_max_steps': 'Límite de pasos'},
    'it': {'ai_title': 'Assistente IA', 'ai_new_chat': 'Nuova conversazione', 'ai_settings': 'Impostazioni IA', 'ai_attach': 'Allega immagini o PDF', 'ai_placeholder': 'Chiedi all’IA di modificare questo documento o allega un’immagine da ricreare…', 'ai_send': 'Invia (Invio)', 'ai_stop': 'Ferma', 'ai_working': 'In corso…', 'ai_api_key': 'Chiave API', 'ai_model': 'ID del modello', 'ai_settings_advanced': 'Avanzate', 'ai_max_steps': 'Limite di passaggi'},
    'ru': {'ai_title': 'ИИ-ассистент', 'ai_new_chat': 'Новый диалог', 'ai_settings': 'Настройки ИИ', 'ai_attach': 'Прикрепить изображения или PDF', 'ai_placeholder': 'Попросите ИИ изменить документ или прикрепите изображение для воссоздания…', 'ai_send': 'Отправить (Enter)', 'ai_stop': 'Остановить', 'ai_working': 'Выполняется…', 'ai_api_key': 'Ключ API', 'ai_model': 'ID модели', 'ai_settings_advanced': 'Дополнительно', 'ai_max_steps': 'Лимит шагов'},
}.items():
    MENU_TRANSLATIONS[_language].update(_values)

# Stacking order.
for _language, _values in {
    'tr': {'element_bring_front': 'Öne Getir (Ctrl+])', 'element_send_back': 'Arkaya Gönder (Ctrl+[)'},
    'fr': {'element_bring_front': 'Mettre au premier plan (Ctrl+])', 'element_send_back': 'Mettre à l’arrière-plan (Ctrl+[)'},
    'de': {'element_bring_front': 'In den Vordergrund (Strg+])', 'element_send_back': 'In den Hintergrund (Strg+[)'},
    'es': {'element_bring_front': 'Traer al frente (Ctrl+])', 'element_send_back': 'Enviar al fondo (Ctrl+[)'},
    'it': {'element_bring_front': 'Porta in primo piano (Ctrl+])', 'element_send_back': 'Porta sullo sfondo (Ctrl+[)'},
    'ru': {'element_bring_front': 'На передний план (Ctrl+])', 'element_send_back': 'На задний план (Ctrl+[)'},
}.items():
    MENU_TRANSLATIONS[_language].update(_values)

# Shapes and lines.
for _language, _values in {
    'tr': ['Şekil seçenekleri', 'Köşe yarıçapı', 'Opaklık', 'Kenar sayısı', 'Yıldız uçları', 'İç yarıçap', 'Çizgi stili', 'Düz', 'Kesikli', 'Noktalı', 'Çizgi seçenekleri', 'Başta ok', 'Sonda ok', 'Yuvarlak dikdörtgen', 'Üçgen', 'Dik üçgen', 'Eşkenar dörtgen', 'Beşgen', 'Altıgen', 'Yıldız', 'Blok ok', 'Konuşma balonu', 'Çizgi (Shift açıyı sabitler)', 'Ok (Shift açıyı sabitler)', 'Şekil', 'Çizgi'],
    'fr': ['Options de forme', 'Rayon des coins', 'Opacité', 'Côtés', 'Branches de l’étoile', 'Rayon intérieur', 'Style de trait', 'Plein', 'Tirets', 'Pointillés', 'Options de ligne', 'Flèche au début', 'Flèche à la fin', 'Rectangle arrondi', 'Triangle', 'Triangle rectangle', 'Losange', 'Pentagone', 'Hexagone', 'Étoile', 'Flèche pleine', 'Bulle', 'Ligne (Maj aimante l’angle)', 'Flèche (Maj aimante l’angle)', 'Forme', 'Ligne'],
    'de': ['Formoptionen', 'Eckenradius', 'Deckkraft', 'Seiten', 'Sternzacken', 'Innenradius', 'Linienstil', 'Durchgezogen', 'Gestrichelt', 'Gepunktet', 'Linienoptionen', 'Pfeil am Anfang', 'Pfeil am Ende', 'Abgerundetes Rechteck', 'Dreieck', 'Rechtwinkliges Dreieck', 'Raute', 'Fünfeck', 'Sechseck', 'Stern', 'Blockpfeil', 'Sprechblase', 'Linie (Umschalt rastet Winkel ein)', 'Pfeil (Umschalt rastet Winkel ein)', 'Form', 'Linie'],
    'es': ['Opciones de forma', 'Radio de esquina', 'Opacidad', 'Lados', 'Puntas de estrella', 'Radio interior', 'Estilo de línea', 'Continua', 'Discontinua', 'Punteada', 'Opciones de línea', 'Flecha al inicio', 'Flecha al final', 'Rectángulo redondeado', 'Triángulo', 'Triángulo rectángulo', 'Rombo', 'Pentágono', 'Hexágono', 'Estrella', 'Flecha de bloque', 'Bocadillo', 'Línea (Mayús ajusta el ángulo)', 'Flecha (Mayús ajusta el ángulo)', 'Forma', 'Línea'],
    'it': ['Opzioni forma', 'Raggio angoli', 'Opacità', 'Lati', 'Punte della stella', 'Raggio interno', 'Stile linea', 'Continua', 'Tratteggiata', 'Punteggiata', 'Opzioni linea', 'Freccia all’inizio', 'Freccia alla fine', 'Rettangolo arrotondato', 'Triangolo', 'Triangolo rettangolo', 'Rombo', 'Pentagono', 'Esagono', 'Stella', 'Freccia piena', 'Fumetto', 'Linea (Maiusc blocca l’angolo)', 'Freccia (Maiusc blocca l’angolo)', 'Forma', 'Linea'],
    'ru': ['Параметры фигуры', 'Радиус углов', 'Непрозрачность', 'Стороны', 'Лучи звезды', 'Внутренний радиус', 'Стиль линии', 'Сплошная', 'Штриховая', 'Пунктирная', 'Параметры линии', 'Стрелка в начале', 'Стрелка в конце', 'Скруглённый прямоугольник', 'Треугольник', 'Прямоугольный треугольник', 'Ромб', 'Пятиугольник', 'Шестиугольник', 'Звезда', 'Блочная стрелка', 'Выноска', 'Линия (Shift фиксирует угол)', 'Стрелка (Shift фиксирует угол)', 'Фигура', 'Линия'],
}.items():
    MENU_TRANSLATIONS[_language].update(zip(['shape_options', 'shape_corner_radius', 'shape_opacity', 'shape_sides', 'shape_star_points', 'shape_star_depth', 'shape_line_style', 'line_solid', 'line_dashed', 'line_dotted', 'line_options', 'line_arrow_start', 'line_arrow_end', 'shape_rounded', 'shape_triangle', 'shape_right_triangle', 'shape_diamond', 'shape_pentagon', 'shape_hexagon', 'shape_star', 'shape_arrow', 'shape_callout', 'tool_line', 'tool_arrow_line', 'tool_shape', 'tool_line_label'], _values))

# AI bar layout.
for _language, _values in {
    'tr': ['Konuşmayı gizle', 'Konuşmayı göster', 'Yana sabitle', 'Altta yüzdür', '{} adım', '1 adım', '{} sorun', '1 sorun'],
    'fr': ['Masquer la conversation', 'Afficher la conversation', 'Ancrer sur le côté', 'Flotter en bas', '{} étapes', '1 étape', '{} problèmes', '1 problème'],
    'de': ['Unterhaltung ausblenden', 'Unterhaltung anzeigen', 'Seitlich andocken', 'Unten schweben', '{} Schritte', '1 Schritt', '{} Probleme', '1 Problem'],
    'es': ['Ocultar conversación', 'Mostrar conversación', 'Acoplar al lateral', 'Flotar abajo', '{} pasos', '1 paso', '{} problemas', '1 problema'],
    'it': ['Nascondi conversazione', 'Mostra conversazione', 'Aggancia di lato', 'Fluttua in basso', '{} passaggi', '1 passaggio', '{} problemi', '1 problema'],
    'ru': ['Скрыть диалог', 'Показать диалог', 'Закрепить сбоку', 'Внизу поверх страницы', 'Шагов: {}', '1 шаг', 'Проблем: {}', '1 проблема'],
}.items():
    MENU_TRANSLATIONS[_language].update(zip(['ai_collapse', 'ai_expand', 'ai_dock', 'ai_undock', 'ai_steps', 'ai_steps_one', 'ai_issues', 'ai_issues_one'], _values))

# Form submission.
for _language, _values in {
    'tr': ['Gönder', 'Bu düğmenin gönderilebilecek bir adresi yok ({}).', 'Göndermeden önce zorunlu alanları doldurun: {}', 'Form verileri ({}) {} adresine gönderilsin mi?', 'Form verileriyle {} adresine e-posta uygulaması açılsın mı?', 'Bağlantı şifreli değil (http); ağdaki başkaları verileri okuyabilir.', 'Form {} adresine gönderiliyor…', 'Form gönderildi', '{} formu kabul etti (HTTP {}).', 'Form gönderildi (HTTP {}).', 'Form gönderilemedi', 'Form {} adresine gönderilemedi: {}', 'Form gönderimi başarısız.', 'Tekrar Dene', 'Form gönderimi'],
    'fr': ['Envoyer', 'Ce bouton n’a pas d’adresse d’envoi utilisable ({}).', 'Remplissez les champs obligatoires avant l’envoi : {}', 'Envoyer les données du formulaire ({}) à {} ?', 'Ouvrir votre messagerie avec les données du formulaire adressées à {} ?', 'La connexion n’est pas chiffrée (http) : d’autres personnes sur le réseau pourraient lire les données.', 'Envoi du formulaire à {}…', 'Formulaire envoyé', '{} a accepté le formulaire (HTTP {}).', 'Formulaire envoyé (HTTP {}).', 'Formulaire non envoyé', 'Le formulaire n’a pas pu être envoyé à {} : {}', 'Échec de l’envoi du formulaire.', 'Réessayer', 'Envoi de formulaire'],
    'de': ['Senden', 'Diese Schaltfläche hat keine Adresse, an die pdfLX senden kann ({}).', 'Füllen Sie vor dem Senden die Pflichtfelder aus: {}', 'Formulardaten ({}) an {} senden?', 'E-Mail-Programm mit den Formulardaten an {} öffnen?', 'Die Verbindung ist nicht verschlüsselt (http); andere im Netzwerk könnten die Daten lesen.', 'Formular wird an {} gesendet…', 'Formular gesendet', '{} hat das Formular angenommen (HTTP {}).', 'Formular gesendet (HTTP {}).', 'Formular nicht gesendet', 'Das Formular konnte nicht an {} gesendet werden: {}', 'Senden des Formulars fehlgeschlagen.', 'Erneut versuchen', 'Formularübermittlung'],
    'es': ['Enviar', 'Este botón no tiene una dirección a la que pdfLX pueda enviar ({}).', 'Rellena los campos obligatorios antes de enviar: {}', '¿Enviar los datos del formulario ({}) a {}?', '¿Abrir tu aplicación de correo con los datos del formulario para {}?', 'La conexión no está cifrada (http); otras personas en la red podrían leer los datos.', 'Enviando el formulario a {}…', 'Formulario enviado', '{} aceptó el formulario (HTTP {}).', 'Formulario enviado (HTTP {}).', 'Formulario no enviado', 'No se pudo enviar el formulario a {}: {}', 'Error al enviar el formulario.', 'Reintentar', 'Envío de formulario'],
    'it': ['Invia', 'Questo pulsante non ha un indirizzo a cui pdfLX possa inviare ({}).', 'Compila i campi obbligatori prima di inviare: {}', 'Inviare i dati del modulo ({}) a {}?', 'Aprire l’app di posta con i dati del modulo per {}?', 'La connessione non è cifrata (http): altri sulla rete potrebbero leggere i dati.', 'Invio del modulo a {}…', 'Modulo inviato', '{} ha accettato il modulo (HTTP {}).', 'Modulo inviato (HTTP {}).', 'Modulo non inviato', 'Impossibile inviare il modulo a {}: {}', 'Invio del modulo non riuscito.', 'Riprova', 'Invio modulo'],
    'ru': ['Отправить', 'У этой кнопки нет адреса, по которому pdfLX может отправить данные ({}).', 'Перед отправкой заполните обязательные поля: {}', 'Отправить данные формы ({}) на {}?', 'Открыть почтовую программу с данными формы для {}?', 'Соединение не зашифровано (http): другие в сети могут прочитать данные.', 'Отправка формы на {}…', 'Форма отправлена', '{} принял форму (HTTP {}).', 'Форма отправлена (HTTP {}).', 'Форма не отправлена', 'Не удалось отправить форму на {}: {}', 'Ошибка отправки формы.', 'Повторить', 'Отправка формы'],
}.items():
    MENU_TRANSLATIONS[_language].update(zip(['submit_send', 'submit_bad_address', 'submit_missing', 'submit_confirm', 'submit_confirm_mail', 'submit_unencrypted', 'submit_sending', 'submit_done_title', 'submit_done', 'submit_done_status', 'submit_failed_title', 'submit_failed', 'submit_failed_status', 'submit_retry', 'submit_mail_subject'], _values))

# Quick fields.
for _language, _values in {
    'tr': ['Hızlı alanlar', 'Sonraki alanın etiketi (isteğe bağlı)', 'Metin', 'Paragraf', 'Tarih', 'E-posta', 'Telefon', 'Sayı', 'Açılır liste', 'Liste', 'Onay kutusu', 'Seçenek', 'İmza', 'Gönder', 'Sıfırla', 'Form stili…', 'Kopyalar…', 'Stili uygula', 'Alanları bul', 'Sekme sırası'],
    'fr': ['Champs rapides', 'Libellé du prochain champ (facultatif)', 'Texte', 'Paragraphe', 'Date', 'E-mail', 'Téléphone', 'Nombre', 'Liste déroulante', 'Liste', 'Case à cocher', 'Bouton radio', 'Signature', 'Envoyer', 'Réinitialiser', 'Style du formulaire…', 'Copies…', 'Appliquer le style', 'Détecter les champs', 'Ordre de tabulation'],
    'de': ['Schnellfelder', 'Beschriftung des nächsten Felds (optional)', 'Text', 'Absatz', 'Datum', 'E-Mail', 'Telefon', 'Zahl', 'Dropdown', 'Liste', 'Kontrollkästchen', 'Optionsfeld', 'Unterschrift', 'Senden', 'Zurücksetzen', 'Formularstil…', 'Kopien…', 'Stil anwenden', 'Felder erkennen', 'Tab-Reihenfolge'],
    'es': ['Campos rápidos', 'Etiqueta del siguiente campo (opcional)', 'Texto', 'Párrafo', 'Fecha', 'Correo', 'Teléfono', 'Número', 'Desplegable', 'Lista', 'Casilla', 'Opción', 'Firma', 'Enviar', 'Restablecer', 'Estilo del formulario…', 'Copias…', 'Aplicar estilo', 'Detectar campos', 'Orden de tabulación'],
    'it': ['Campi rapidi', 'Etichetta del prossimo campo (facoltativa)', 'Testo', 'Paragrafo', 'Data', 'Email', 'Telefono', 'Numero', 'Menu a discesa', 'Elenco', 'Casella', 'Opzione', 'Firma', 'Invia', 'Reimposta', 'Stile modulo…', 'Copie…', 'Applica stile', 'Rileva campi', 'Ordine di tabulazione'],
    'ru': ['Быстрые поля', 'Подпись следующего поля (необязательно)', 'Текст', 'Абзац', 'Дата', 'Эл. почта', 'Телефон', 'Число', 'Список выбора', 'Список', 'Флажок', 'Переключатель', 'Подпись', 'Отправить', 'Сбросить', 'Стиль формы…', 'Копии…', 'Применить стиль', 'Найти поля', 'Порядок обхода'],
}.items():
    MENU_TRANSLATIONS[_language].update(zip(['qf_title', 'qf_label_hint', 'qf_text', 'qf_multiline', 'qf_date', 'qf_email', 'qf_phone', 'qf_number', 'qf_dropdown', 'qf_list', 'qf_checkbox', 'qf_radio', 'qf_signature', 'qf_submit', 'qf_reset', 'qf_style', 'qf_copies', 'qf_apply_style', 'qf_detect', 'qf_tab_order'], _values))

# Forms menu: one entry opens the sidebar for building and filling.
for _language, _values in {
    'tr': {'tool_fill_forms': 'Form Oluştur ve Doldur…'},
    'fr': {'tool_fill_forms': 'Créer et remplir des formulaires…'},
    'de': {'tool_fill_forms': 'Formulare erstellen und ausfüllen…'},
    'es': {'tool_fill_forms': 'Crear y rellenar formularios…'},
    'it': {'tool_fill_forms': 'Crea e compila moduli…'},
    'ru': {'tool_fill_forms': 'Создание и заполнение форм…'},
}.items():
    MENU_TRANSLATIONS[_language].update(_values)

# Form sidebar layout: section and tool names.
for _language, _values in {
    'tr': {'qf_title': 'Alan ekle', 'qf_copies': 'Çoklu kopya', 'qf_section_style': 'Stil', 'qf_section_tools': 'Araçlar',
           'qf_section_fields': 'Alanlar', 'qf_scripts': 'Alan betikleri', 'qf_group_inputs': 'Girişler',
           'qf_group_choices': 'Seçimler', 'qf_group_buttons': 'Düğmeler ve imza'},
    'fr': {'qf_title': 'Ajouter des champs', 'qf_copies': 'Copies multiples', 'qf_section_style': 'Style',
           'qf_section_tools': 'Outils', 'qf_section_fields': 'Champs', 'qf_scripts': 'Scripts du champ',
           'qf_group_inputs': 'Saisies', 'qf_group_choices': 'Choix', 'qf_group_buttons': 'Boutons et signature'},
    'de': {'qf_title': 'Felder hinzufügen', 'qf_copies': 'Mehrfachkopien', 'qf_section_style': 'Stil',
           'qf_section_tools': 'Werkzeuge', 'qf_section_fields': 'Felder', 'qf_scripts': 'Feldskripte',
           'qf_group_inputs': 'Eingaben', 'qf_group_choices': 'Auswahl', 'qf_group_buttons': 'Schaltflächen und Signatur'},
    'es': {'qf_title': 'Añadir campos', 'qf_copies': 'Copias múltiples', 'qf_section_style': 'Estilo',
           'qf_section_tools': 'Herramientas', 'qf_section_fields': 'Campos', 'qf_scripts': 'Scripts del campo',
           'qf_group_inputs': 'Entradas', 'qf_group_choices': 'Opciones', 'qf_group_buttons': 'Botones y firma'},
    'it': {'qf_title': 'Aggiungi campi', 'qf_copies': 'Copie multiple', 'qf_section_style': 'Stile',
           'qf_section_tools': 'Strumenti', 'qf_section_fields': 'Campi', 'qf_scripts': 'Script del campo',
           'qf_group_inputs': 'Input', 'qf_group_choices': 'Scelte', 'qf_group_buttons': 'Pulsanti e firma'},
    'ru': {'qf_title': 'Добавить поля', 'qf_copies': 'Несколько копий', 'qf_section_style': 'Стиль',
           'qf_section_tools': 'Инструменты', 'qf_section_fields': 'Поля', 'qf_scripts': 'Скрипты поля',
           'qf_group_inputs': 'Ввод', 'qf_group_choices': 'Выбор', 'qf_group_buttons': 'Кнопки и подпись'},
}.items():
    MENU_TRANSLATIONS[_language].update(_values)

# Reorganized menus.
for _language, _values in {
    'tr': {'menu_group_create': 'Oluştur', 'menu_group_edit': 'Düzenle ve Ekle', 'menu_group_forms': 'Formlar',
           'menu_preferences': 'Tercihler', 'menu_more_tools': 'Diğer araçlar', 'menu_section_review': 'İnceleme',
           'menu_section_page_look': 'Sayfa görünümü', 'menu_section_protect': 'Koruma', 'menu_group_annotate': 'Açıklama ve İnceleme'},
    'fr': {'menu_group_create': 'Créer', 'menu_group_edit': 'Modifier et insérer', 'menu_group_forms': 'Formulaires',
           'menu_preferences': 'Préférences', 'menu_more_tools': 'Autres outils', 'menu_section_review': 'Révision',
           'menu_section_page_look': 'Apparence des pages', 'menu_section_protect': 'Protection', 'menu_group_annotate': 'Annoter et réviser'},
    'de': {'menu_group_create': 'Erstellen', 'menu_group_edit': 'Bearbeiten und einfügen', 'menu_group_forms': 'Formulare',
           'menu_preferences': 'Einstellungen', 'menu_more_tools': 'Weitere Werkzeuge', 'menu_section_review': 'Prüfen',
           'menu_section_page_look': 'Seitengestaltung', 'menu_section_protect': 'Schützen', 'menu_group_annotate': 'Kommentieren und prüfen'},
    'es': {'menu_group_create': 'Crear', 'menu_group_edit': 'Editar e insertar', 'menu_group_forms': 'Formularios',
           'menu_preferences': 'Preferencias', 'menu_more_tools': 'Más herramientas', 'menu_section_review': 'Revisión',
           'menu_section_page_look': 'Aspecto de página', 'menu_section_protect': 'Proteger', 'menu_group_annotate': 'Anotar y revisar'},
    'it': {'menu_group_create': 'Crea', 'menu_group_edit': 'Modifica e inserisci', 'menu_group_forms': 'Moduli',
           'menu_preferences': 'Preferenze', 'menu_more_tools': 'Altri strumenti', 'menu_section_review': 'Revisione',
           'menu_section_page_look': 'Aspetto pagina', 'menu_section_protect': 'Protezione', 'menu_group_annotate': 'Annota e rivedi'},
    'ru': {'menu_group_create': 'Создать', 'menu_group_edit': 'Правка и вставка', 'menu_group_forms': 'Формы',
           'menu_preferences': 'Настройки', 'menu_more_tools': 'Другие инструменты', 'menu_section_review': 'Рецензирование',
           'menu_section_page_look': 'Оформление страниц', 'menu_section_protect': 'Защита', 'menu_group_annotate': 'Комментарии и рецензия'},
}.items():
    MENU_TRANSLATIONS[_language].update(_values)
