"""Named characters for the searchable symbol and emoji palette."""

SYMBOL_CATEGORIES = (
    ('palette_review', (
        ('✓', 'Check mark approved'), ('✔', 'Heavy check mark done'),
        ('✕', 'Cross multiplication'), ('✗', 'Cross mark rejected'),
        ('☑', 'Checked ballot box'), ('☒', 'Crossed ballot box'),
        ('☐', 'Empty checkbox'), ('★', 'Filled star'), ('☆', 'Outline star'),
        ('•', 'Bullet'), ('◦', 'Outline bullet'), ('※', 'Reference mark'),
        ('†', 'Dagger footnote'), ('‡', 'Double dagger footnote'),
        ('§', 'Section sign'), ('¶', 'Paragraph sign'),
    )),
    ('palette_arrows', (
        ('←', 'Left arrow'), ('↑', 'Up arrow'), ('→', 'Right arrow'),
        ('↓', 'Down arrow'), ('↔', 'Left right arrow'), ('↕', 'Up down arrow'),
        ('↖', 'Upper left arrow'), ('↗', 'Upper right arrow'),
        ('↘', 'Lower right arrow'), ('↙', 'Lower left arrow'),
        ('↩', 'Return left arrow'), ('↪', 'Return right arrow'),
        ('⇐', 'Double left arrow'), ('⇒', 'Double right arrow implies'),
        ('⇔', 'Double left right arrow equivalent'), ('➜', 'Heavy right arrow'),
        ('➔', 'Right arrow'), ('↻', 'Clockwise arrow'), ('↺', 'Counterclockwise arrow'),
    )),
    ('palette_math', (
        ('+', 'Plus add'), ('−', 'Minus subtract'), ('×', 'Multiply times'),
        ('÷', 'Divide'), ('=', 'Equals'), ('±', 'Plus minus'),
        ('∓', 'Minus plus'), ('≠', 'Not equal'), ('≈', 'Approximately equal'),
        ('≡', 'Identical equivalent'), ('≤', 'Less than or equal'),
        ('≥', 'Greater than or equal'), ('∞', 'Infinity'), ('√', 'Square root'),
        ('∑', 'Sum summation'), ('∏', 'Product'), ('∫', 'Integral'),
        ('∂', 'Partial derivative'), ('∆', 'Delta change'), ('∇', 'Nabla gradient'),
        ('∈', 'Element of'), ('∉', 'Not an element of'), ('∅', 'Empty set'),
        ('∪', 'Union'), ('∩', 'Intersection'), ('⊂', 'Subset'),
        ('⊆', 'Subset or equal'), ('∝', 'Proportional to'), ('°', 'Degree'),
        ('%', 'Percent'), ('‰', 'Per mille'), ('²', 'Superscript two squared'),
        ('³', 'Superscript three cubed'), ('½', 'One half fraction'),
        ('¼', 'One quarter fraction'), ('¾', 'Three quarters fraction'),
    )),
    ('palette_currency', (
        ('©', 'Copyright'), ('®', 'Registered trademark'), ('™', 'Trademark'),
        ('€', 'Euro'), ('$', 'Dollar'), ('£', 'Pound sterling'), ('¥', 'Yen yuan'),
        ('₹', 'Indian rupee'), ('₩', 'Korean won'), ('₺', 'Turkish lira'),
        ('₽', 'Russian ruble'), ('₴', 'Ukrainian hryvnia'), ('¢', 'Cent'),
        ('¤', 'Currency'), ('№', 'Number sign'),
    )),
    ('palette_shapes', (
        ('●', 'Filled circle'), ('○', 'Outline circle'), ('◉', 'Target circle'),
        ('◯', 'Large outline circle'), ('⬤', 'Large filled circle'),
        ('■', 'Filled square'), ('□', 'Outline square'), ('▪', 'Small filled square'),
        ('▫', 'Small outline square'), ('◆', 'Filled diamond'), ('◇', 'Outline diamond'),
        ('▲', 'Up triangle'), ('△', 'Outline up triangle'), ('▼', 'Down triangle'),
        ('▽', 'Outline down triangle'), ('▶', 'Right triangle'), ('◀', 'Left triangle'),
        ('…', 'Ellipsis'), ('–', 'En dash'), ('—', 'Em dash'),
        ('«', 'Left quotation marks'), ('»', 'Right quotation marks'),
        ('“', 'Opening quotation mark'), ('”', 'Closing quotation mark'),
        ('‘', 'Opening single quotation mark'), ('’', 'Closing single quotation mark'),
    )),
    ('palette_greek', (
        ('α', 'Alpha'), ('β', 'Beta'), ('γ', 'Gamma'), ('δ', 'Delta'),
        ('ε', 'Epsilon'), ('ζ', 'Zeta'), ('η', 'Eta'), ('θ', 'Theta'),
        ('λ', 'Lambda'), ('μ', 'Mu micro'), ('ν', 'Nu'), ('ξ', 'Xi'),
        ('π', 'Pi'), ('ρ', 'Rho'), ('σ', 'Sigma'), ('τ', 'Tau'),
        ('φ', 'Phi'), ('χ', 'Chi'), ('ψ', 'Psi'), ('ω', 'Omega'),
        ('Γ', 'Capital gamma'), ('Δ', 'Capital delta'), ('Θ', 'Capital theta'),
        ('Λ', 'Capital lambda'), ('Π', 'Capital pi'), ('Σ', 'Capital sigma'),
        ('Φ', 'Capital phi'), ('Ψ', 'Capital psi'), ('Ω', 'Capital omega ohm'),
    )),
)

EMOJI_CATEGORIES = (
    ('palette_emoji_review', (
        ('👍', 'Thumbs up approve'), ('👎', 'Thumbs down reject'),
        ('✅', 'Check mark complete approved'), ('❌', 'Cross mark rejected'),
        ('⚠️', 'Warning caution'), ('🚫', 'Prohibited stop'), ('⛔', 'No entry'),
        ('ℹ️', 'Information'), ('❓', 'Question'), ('❗', 'Exclamation important'),
        ('‼️', 'Double exclamation urgent'), ('⁉️', 'Exclamation question'),
        ('🔴', 'Red circle status'), ('🟠', 'Orange circle status'),
        ('🟡', 'Yellow circle status'), ('🟢', 'Green circle status'),
        ('🔵', 'Blue circle status'), ('🟣', 'Purple circle status'),
        ('🔒', 'Locked private'), ('🔓', 'Unlocked'), ('🔐', 'Secure lock key'),
        ('🛡️', 'Shield protection'), ('⭐', 'Star favorite'), ('🎯', 'Target goal'),
        ('💯', 'Hundred points perfect'), ('🏆', 'Trophy award'),
    )),
    ('palette_faces', (
        ('😀', 'Grinning smile happy'), ('😃', 'Smiling happy'),
        ('😄', 'Smiling eyes happy'), ('😁', 'Beaming grin'), ('😆', 'Laughing'),
        ('😅', 'Smiling sweat relieved'), ('😂', 'Tears of joy laughing'),
        ('🤣', 'Rolling laughing'), ('😊', 'Smiling blush'), ('🙂', 'Slight smile'),
        ('🙃', 'Upside down face'), ('😉', 'Winking'), ('😍', 'Heart eyes love'),
        ('🥰', 'Smiling hearts love'), ('😘', 'Blowing a kiss'), ('😎', 'Cool sunglasses'),
        ('🤓', 'Nerd glasses'), ('🧐', 'Monocle inspect'), ('🤔', 'Thinking'),
        ('🤨', 'Raised eyebrow skeptical'), ('😐', 'Neutral face'), ('😑', 'Expressionless'),
        ('😶', 'Silent no mouth'), ('🙄', 'Rolling eyes'), ('😏', 'Smirking'),
        ('😴', 'Sleeping'), ('🥱', 'Yawning'), ('😮', 'Surprised open mouth'),
        ('😲', 'Astonished'), ('😳', 'Flushed embarrassed'), ('🥺', 'Pleading'),
        ('😢', 'Crying sad'), ('😭', 'Sobbing crying'), ('😤', 'Frustrated'),
        ('😠', 'Angry'), ('😡', 'Very angry'), ('🤯', 'Mind blown'),
        ('😱', 'Screaming shocked'), ('🤩', 'Star struck excited'), ('🥳', 'Party celebration'),
    )),
    ('palette_gestures', (
        ('👋', 'Waving hello goodbye'), ('🤚', 'Raised back hand'), ('✋', 'Raised hand stop'),
        ('👌', 'OK hand'), ('✌️', 'Victory peace'), ('🤞', 'Crossed fingers luck'),
        ('🤟', 'Love you gesture'), ('🤘', 'Rock on horns'), ('🤙', 'Call me'),
        ('👈', 'Point left'), ('👉', 'Point right'), ('👆', 'Point up'), ('👇', 'Point down'),
        ('☝️', 'Index pointing up'), ('👏', 'Clapping applause'), ('🙌', 'Celebration hands'),
        ('👐', 'Open hands'), ('🤝', 'Handshake agreement'), ('🙏', 'Thanks prayer please'),
        ('💪', 'Strong flexed biceps'), ('✍️', 'Writing hand signature'), ('👀', 'Eyes look'),
    )),
    ('palette_work', (
        ('📝', 'Memo note write'), ('📌', 'Pushpin pin'), ('📍', 'Location pin'),
        ('📎', 'Paperclip attachment'), ('🖇️', 'Linked paperclips'), ('✏️', 'Pencil edit'),
        ('🖊️', 'Pen write'), ('🖍️', 'Crayon'), ('📄', 'Document page'),
        ('📃', 'Page with curl'), ('📑', 'Bookmark tabs'), ('📋', 'Clipboard checklist'),
        ('📁', 'Folder'), ('📂', 'Open folder'), ('🗂️', 'Card index dividers'),
        ('📚', 'Books library'), ('📖', 'Open book'), ('🔖', 'Bookmark'),
        ('📅', 'Calendar date'), ('🗓️', 'Calendar schedule'), ('⏰', 'Alarm clock'),
        ('⏳', 'Hourglass waiting'), ('⌛', 'Hourglass finished'), ('⏱️', 'Stopwatch timer'),
        ('💼', 'Briefcase business'), ('💻', 'Laptop computer'), ('🖥️', 'Desktop computer'),
        ('🖨️', 'Printer print'), ('📱', 'Phone mobile'), ('✉️', 'Envelope mail'),
        ('📧', 'Email'), ('📬', 'Mailbox mail'), ('☎️', 'Telephone call'),
        ('📞', 'Telephone receiver'), ('📢', 'Announcement loudspeaker'), ('📣', 'Megaphone'),
        ('💬', 'Speech bubble comment'), ('💭', 'Thought bubble'), ('🔍', 'Search magnifying glass'),
        ('💡', 'Idea light bulb'), ('⚙️', 'Gear settings'), ('🛠️', 'Tools repair'),
        ('🔧', 'Wrench fix'), ('🔑', 'Key access'), ('🗑️', 'Trash delete'),
        ('📊', 'Bar chart statistics'), ('📈', 'Chart increasing growth'),
        ('📉', 'Chart decreasing decline'), ('💰', 'Money bag budget'), ('💳', 'Credit card payment'),
    )),
    ('palette_hearts', (
        ('❤️', 'Red heart love'), ('🧡', 'Orange heart'), ('💛', 'Yellow heart'),
        ('💚', 'Green heart'), ('💙', 'Blue heart'), ('💜', 'Purple heart'),
        ('🖤', 'Black heart'), ('🤍', 'White heart'), ('🤎', 'Brown heart'),
        ('💔', 'Broken heart'), ('💕', 'Two hearts'), ('💖', 'Sparkling heart'),
        ('💗', 'Growing heart'), ('💝', 'Heart gift'), ('✨', 'Sparkles'),
        ('🌟', 'Glowing star'), ('🎉', 'Party popper celebration'), ('🎊', 'Confetti celebration'),
        ('🎈', 'Balloon'), ('🎁', 'Gift present'), ('🎂', 'Birthday cake'),
        ('🥂', 'Cheers glasses'), ('🏅', 'Medal'), ('🎖️', 'Award medal'),
        ('🎵', 'Music note'), ('🎶', 'Music notes'), ('🔥', 'Fire hot'), ('🚀', 'Rocket launch'),
    )),
    ('palette_nature', (
        ('☀️', 'Sun sunny'), ('🌤️', 'Sun small cloud'), ('☁️', 'Cloud cloudy'),
        ('🌧️', 'Rain weather'), ('⛈️', 'Thunderstorm'), ('❄️', 'Snow snowflake'),
        ('🌈', 'Rainbow'), ('🌙', 'Moon night'), ('🌍', 'Earth Europe Africa globe'),
        ('🌎', 'Earth Americas globe'), ('🌏', 'Earth Asia globe'), ('🌱', 'Seedling plant growth'),
        ('🌿', 'Herb leaves'), ('🍀', 'Four leaf clover luck'), ('🌻', 'Sunflower'),
        ('🌷', 'Tulip flower'), ('🌸', 'Cherry blossom'), ('🌹', 'Rose flower'),
        ('🌳', 'Tree'), ('🐶', 'Dog'), ('🐱', 'Cat'), ('🐭', 'Mouse'),
        ('🐰', 'Rabbit'), ('🦊', 'Fox'), ('🐻', 'Bear'), ('🐼', 'Panda'),
        ('🐨', 'Koala'), ('🦁', 'Lion'), ('🐸', 'Frog'), ('🐝', 'Bee'),
        ('🦋', 'Butterfly'), ('🐢', 'Turtle'), ('🐬', 'Dolphin'), ('🐟', 'Fish'),
    )),
    ('palette_everyday', (
        ('☕', 'Coffee hot drink'), ('🍵', 'Tea'), ('🍎', 'Apple fruit'), ('🍓', 'Strawberry'),
        ('🍕', 'Pizza'), ('🍔', 'Burger'), ('🍰', 'Cake dessert'), ('🍽️', 'Plate meal food'),
        ('🏠', 'House home'), ('🏢', 'Office building'), ('🏥', 'Hospital health'),
        ('🏫', 'School education'), ('🚗', 'Car'), ('🚕', 'Taxi'), ('🚌', 'Bus'),
        ('🚲', 'Bicycle'), ('🚆', 'Train'), ('✈️', 'Airplane travel'), ('🚢', 'Ship boat'),
        ('🧳', 'Suitcase luggage'), ('🗺️', 'Map'), ('🧭', 'Compass direction'),
        ('⚽', 'Football soccer'), ('🏀', 'Basketball'), ('🎾', 'Tennis'),
        ('🎮', 'Video game controller'), ('🎨', 'Art palette'), ('📷', 'Camera photo'),
        ('🎬', 'Movie film'), ('🎧', 'Headphones audio'), ('🎤', 'Microphone'),
        ('🩺', 'Stethoscope medical'), ('💊', 'Pill medicine'), ('🧪', 'Test tube science'),
        ('🔬', 'Microscope research'), ('🧲', 'Magnet'), ('🔋', 'Battery power'),
        ('♻️', 'Recycle recycling'), ('💧', 'Water drop'), ('⚡', 'Lightning energy'),
    )),
)
